### ISSUE TITLE
Users / Authentication things to decide

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#115]
@chrisdburr it would be great if we could have your thoughts on some of the following questions:

* Do we want users to be in "groups", such that all members of a group can see and edit a case if and only if they are in the same group as the "owner" of the case?  (This is the default that we are looking at at the moment).
* If so, should users be allowed to choose their group when they sign up?   Should they be presented with a dropdown of all groups (meaning that anyone would be able to see what groups exist)?
* Should users be able to be members of more than one group?  If so, when creating a case, they would need to decide what group(s) can see the case (and cases would effectively be owned by groups rather than users) 
* Do we imagine a situation where users/groups would have different levels of access to a case, e.g. can read but not edit?   Simple example would be that only the user that created the case can edit it, but anyone on their group(s) could view it.
* Would people be able to change groups?   Or could this be done by an admin?  
* How do we want to add users?   Can anyone just sign up, or should an admin have a process to add them?   If the former, do we want some sort of email verification?

We are starting work now on a first iteration that allows anyone to sign-up and then sign-in, and API calls will check for an authentication token, but for future iterations we will need to make some decisions on questions like this...

**Comment by chrisdburr** [comment]
> * Do we want users to be in "groups", such that all members of a group can see and edit a case if and only if they are in the same group as the "owner" of the case?  (This is the default that we are looking at at the moment).

Yes. This seems like a sensible default.


> * If so, should users be allowed to choose their group when they sign up?   Should they be presented with a dropdown of all groups (meaning that anyone would be able to see what groups exist)?

Is there an option where the group owner/admin can invite or add users? 

> * Should users be able to be members of more than one group?  If so, when creating a case, they would need to decide what group(s) can see the case (and cases would effectively be owned by groups rather than users) 

Yes. Ideally users should be able to be members of multiple groups.

> * Do we imagine a situation where users/groups would have different levels of access to a case, e.g. can read but not edit?   Simple example would be that only the user that created the case can edit it, but anyone on their group(s) could view it.

Seems like a good additional feature if it's easy enough to implement.

> * Would people be able to change groups?   Or could this be done by an admin?  

I think having an admin feature would make most sense (re. above answer).

> * How do we want to add users?   Can anyone just sign up, or should an admin have a process to add them?   If the former, do we want some sort of email verification?

Ideally, both. So, for instance, if I were a new user I could sign up and then just build my own cases. But you could also add me to existing ones if you were an existing admin. Some form of verification seems sensible. Happy for it to just be username and password, or email authentication if there's an existing plugin.

> We are starting work now on a first iteration that allows anyone to sign-up and then sign-in, and API calls will check for an authentication token, but for future iterations we will need to make some decisions on questions like this...

Thanks. Happy to discuss more next week.

**Comment by chrisdburr** [comment]
> Who can create groups?
- Anyone

> Does each group have an admin/owner or do we just have an "admin" group that overseas everything?
- If the person who creates the group can be default owner/admin that should be fine. 

> Can everyone see all users? All groups?
- Default: no
- If owners of groups want to add users, perhaps this can just be done via an invite mechanism that has to be accepted by the user.

**Comment by kallewesterling** [comment]
Suggestion to close this issue, or -- if there are important remaining action items from this, to move them into a new issue (backlinking here) with an active verb in the title of the issue.
