### ISSUE TITLE
Proposed API endpoints for group/user management

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#134]
First suggestion...
For groups, 
* GET request to `/groups/`: list all groups that the logged-in user belongs to.
  - returns `[{id: <int:id>, name: {str:name}, ... ]`
* POST request to `/groups/`: create a new group, with the logged-in user as the owner.
  - payload `{name: <str:name>}`
* GET request to `/groups/<id>/`: Return details of the group, IF the logged-in user is the owner.
  - return `{id: <int:id>, name: <str:name>, members: [{<id: <int:id>, email: <str:email>},...], owner: {id:<int:id>, email:<str:email>}}`
* DELETE or PUT request to `/groups/<id>/`: Delete group or edit group attributes, IF the logged-in user is the owner.
  - payload for PUT is desired key/value to change, e.g. `{members: [{<id: <int:id>, email: <str:email>},...]`

I _think_ that should cover things - maybe adding/removing members via a PUT request could be clunky, as it would need to send the whole list of members rather than just the user to be added or removed, but we can try it..?

**Comment by mhauru** [comment]
Ah, good point with the PUT, I hadn't thought of the case of an admin wanting to remove users. I don't think sending back the whole list is too cumbersome, I'll probably make an input box with a comma-separated list of users that you can add to/remove from.

If the PUT request needs to have user IDs in the payload, then the frontend would need a way to query for IDs. Would it work if it just had emails/usernames?

Would `/groups/` return value includes owners? I need some way to list all groups that a user is an owner of, could filter that.

What about invites? I think we might need two lists of users for each group, one for users that have been approved to join, and one for users that have joined. Although, now that I think about it, how bad would it be if an admin could add group members without the members consent?
