### ISSUE TITLE
The end is nigh

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/AssurancePlatform#144]
Markus:
* [x] Create new group button in edit permissions view
* [x] Favicon
* [ ] Test on Windows
* [x] Check if https://github.com/alan-turing-institute/AssurancePlatform/issues/48 still happens
* [x] Fix a bug with deleting an item crashing on Chrome

Nick:
* [ ] Test on Safari
* [x] Backend tests for groups and users
* [x] Frontend tests groups and users
* [ ] Simplify Azure setup, remove dev

???:
* [x] update package.json with newer npm audit upgrade.
* [ ] Clean up debug code
* [ ] Documentation for everything
    * [ ] READMEs
    * [ ] Maybe some code documentation
    * [ ] Docker instructions (can just be pull existing images and do docker run).
* [ ] Link to main assurance platform
* [x] Remove requirements.txt from root dir
* [x] replace psycopg2 with psycopg2-binary in eap_backend/requirements.txt
* [x] Reorder navbar links
* [x] Test on touch screen and various form factors
* [x] Switch from emails to usernames

Maybe not:
* [ ] Make an "everyone" group?

**Comment by mhauru** [comment]
I tried `npm audit fix` to get rid of some of the security warnings, but it only helps for a handful of them. Even after a full `npm upgrade`, we are still left with `48 vulnerabilities (13 moderate, 25 high, 10 critical)`.

**Comment by kallewesterling** [comment]
Suggestion to close this issue, or -- if there are important remaining action items from this, to move them into a new issue (backlinking here) with an active verb in the title of the issue.
