### ISSUE TITLE
Add repo contributor guides and DOI

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/AssurancePlatform#156]
A CONTRIBUTING.md makes it easy for friends of this project to know how to engage with and contribute to the work. I also didn't spot a DOI in the CITATION.cff or README. 

The below materials descibe how and why to include these files/features:

From [Open WIN](https://open.win.ox.ac.uk/pages/open-science/community/Open-WIN-Community/docs/gitlab/repo-include/) and Open Life Science ([CITATION.cff](https://docs.google.com/presentation/d/1V2-6PbJiPOYGBGsHJbKj9Y49iPHsHnAIKnhCuV40U3I/edit#slide=id.g2224fafcba8_0_37)

## How to fix the issue

- [x] Add CONTRIBUTING.md
- [x] Add DOI in CITATION.cff
- [x] Add DOI in README.md

**Comment by AoifeHughes** [comment]
https://github.com/alan-turing-institute/AssurancePlatform/pull/192 - I'll get on the DOI issue now, but please feel free to add more details here, I didn't have everyone's ORCID for instance.

**Comment by cassgvp** [comment]
Thanks, @AoifeHughes :) My ORCID: [0000-0002-8584-4637](https://orcid.org/0000-0002-8584-4637).

**Comment by kallewesterling** [comment]
Looks like this is done and can be closed as finished?
