### ISSUE TITLE
Frontend: Mermaid JS cheetsheet and designs

### ISSUE THREAD

**Issue by entopia** [alan-turing-institute/AssurancePlatform#16]
All preferences for chart themes:
https://jojozhuang.github.io/tutorial/mermaid-cheat-sheet/

Theme Configuration: 
https://github.com/mermaid-js/mermaid/blob/develop/docs/theming.md

Tutorials: 
https://mermaid-js.github.io/mermaid/#/Tutorials

Basic Configurations: 
```
{
  "theme": "base",
    "flowchart": { "curve": "linear" },
  "themeVariables": {
    "primaryColor": "#fff000",
    "background": "#f0f0f0",
    "nodeBorder" : "#004990",
    "mainBkg" : "#c9d7e4",
    "nodeTextColor" : "#274059",
    "fontFamily": "arial",
    "fontSize": "18px",
    "darkMode": "true"
 }
}
```

**Comment by chrisdburr** [comment]
Closing this issue. Please refer to https://mermaid.js.org/intro/ for any information about mermaid use and integration.
