### ISSUE TITLE
Export to image file svg, png, pdf, etc. and include a metadata json in file for importing?

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#167]
See #96 also

**Comment by chrisdburr** [comment]
What are you thinking of including in the `.json` file beyond the current elements and structure of the assurance case?

**Comment by AoifeHughes** [comment]
Not in the JSON, rather if we export as a svg or png for example, we can put the JSON in as meta data to those files. So you could re upload an image file and edit it directly. 2-in-1 kinda

**Comment by chrisdburr** [comment]
Oh, cool. Didn't realise that could be done 😄

**Comment by AoifeHughes** [comment]
https://github.com/mermaid-js/mermaid-cli is the solution, but trying to decide to do via backend or frontend 🤔

**Comment by AoifeHughes** [comment]
TODO: add https://github.com/mermaid-js/mermaid-cli to backend deps. Can't compile for front end due to requirements

**Comment by AoifeHughes** [comment]
see https://github.com/alan-turing-institute/AssurancePlatform/pull/216

**Comment by AoifeHughes** [comment]
This has been added to the live Azure version, but there's currently a bug that's not exporting properly due to Docker implementation of this! So that's now an active bug
