### ISSUE TITLE
[epic] Add user guidance enhancements to interface (e.g. ℹ tooltips to help explain options)

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#170]

**Comment by AoifeHughes** [comment]
More info needed - would be great to get some examples, maybe annotated screenshots of this!

**Comment by chrisdburr** [comment]
I think there's a broader piece of work on general documentation connected to this. For instance, if we're going to have tooltips, the content of them may need to link to relevant explanatory pages on our site:

https://alan-turing-institute.github.io/AssurancePlatform/about/

I'll set up another issue to start the planning and drafting of these pages, as I've been working on some of this already. @kallewesterling it would be good to get your eyes on this (e.g. sense checking and reviewing the content).

**Comment by kallewesterling** [comment]
Happy to! This is the issue, right? Just to make sure they're linked together:
- [ ] https://github.com/alan-turing-institute/AssurancePlatform/issues/190

**Comment by AoifeHughes** [comment]
see: https://github.com/alan-turing-institute/AssurancePlatform/issues/191#issuecomment-1658048893

**Comment by kallewesterling** [comment]
> @RichGriff, as discussed, if you make any headway with this, you can grab the definitions of the various elements from the following document: https://hackmd.io/F0EeWVrxRGe8f93KGOIzjA?view#2-Description-of-Core-Elements

Looks like this is implemented in the overhaul of the interface currently. For further development, we should write user stories about the _specific_ user guidance enhancements that we'd like to have, and link it to this overarching epic (this issue).

**Comment by chrisdburr** [comment]
Next step is for this issue to be converted into an actionable user story.

**Comment by chrisdburr** [comment]
Closing. Will reopen as proper user story if still needed.
