### ISSUE TITLE
Define an "official" repo format for importing arguments, and also allow users to add their own or custom ones.

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#173]

**Comment by AoifeHughes** [comment]
Draft pass at this is done in https://github.com/alan-turing-institute/AssurancePlatform/pull/217

**Comment by kallewesterling** [comment]
@AoifeHughes I can't see any examples of repo format in #217, but I can certainly try to come up with a first draft of a solution to this one, if it's helpful?

**Comment by kallewesterling** [comment]
@AoifeHughes, FYI: Moving this to "Won't have" for now, as it's not a prioritised issue, nor a feasible one to complete in the next sprint. It's also in "Needs more info" as there are unanswered questions regarding the implementation of this.
