### ISSUE TITLE
Add support for multiple schemas or standards (e.g. GSN, CAE)

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#176]
We want: Long-term consistency with assurance standards.

**Comment by AoifeHughes** [comment]
see https://github.com/alan-turing-institute/AssurancePlatform/issues/175

**Comment by kallewesterling** [comment]
@cptanalatriste We should have a chat about how we can relate conversations about #412 to this one, i.e. how we can best build a flexible enough structure in the backend to support multiple schemas/standards in other "layers"..

**Comment by chrisdburr** [comment]
Closing. Will reopen with proper requirements and plan.
