### ISSUE TITLE
User authentication improvements (e.g. adding Auth0?)

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#178]

**Comment by AoifeHughes** [comment]
This might actually be super useful to remove liability for data storage.

**Comment by AoifeHughes** [comment]
Need to investigate further

**Comment by chrisdburr** [comment]
> Leaving a comment here as a follow-up from a small meeting @chrisdburr & I just had.
> 
>     * We started by clarifying that the idea would be to potentially use the [OAuth](https://oauth.net/2/) functions of GitHub's [REST API](https://docs.github.com/en/rest) for the authentication (sorry if that feels a bit pedantic, but confusingly there's a startup offering user management & single-sign-on logins with the name https://auth0.com/ 😂)
> 
>     * Using GHs OAuth2 for login/authentication will potentially minimize the types of data the Assurance Platform needs to store, but it will still require a local database for the platform, to store the OAuth2 tokens needed to interact (`access_token`, `refresh_token`, `token_experiation_date`)
> 
>     * We also brainstormed a bit on using the local database for storing the private files, but then using the GH API to make pull requests to a public repo for the cases that people want to release publicly, which would allow the Assurance Platform not having to worry about how to moderate/people publishing private information on the platform etc.
> 
> 
> The main open question we had was: Does the assurance platform want/need to be able to send emails to its users (or have other ways to contact them)? I don't know the GH API docs on top of my head for this, depending on the scope one requests one can probably request the email address when users login with GH (but that means having personal information) or offer a way to email through GH?
> 
> @chrisdburr: please add to this if I forgot any of the questions!
> 
> @AoifeHughes: As Chris already mentioned on Slack, if you're not familiar with OAuth2 and the implementation of it yet I'd be more than happy to provide support (the dance between the two different involved web servers & user's browser can be a lot the first time one encounters it in a web setting!)

That's everything, @gedankenstuecke. Many thanks for the comprehensive summary and support.

**Comment by AoifeHughes** [comment]
Thanks both. @chrisdburr just to clarify, I'll start adding Github as a login option do we:

1. Want users to be able to use the current method of creating an account as well, or to remove it?
2. If Github becomes the only method of logging in then running it locally will be a pain with having someone need to register the app with github to setup the API keys etc. This isn't a problem for the Azure instance as it'll be setup once and done. 
3. We still have the issue of data storage, as established in our slack comms, we will still need to store things in our DBs.

**Comment by chrisdburr** [comment]
>     1. Want users to be able to use the current method of creating an account as well, or to remove it?

I would have suggested removing it, until I saw your next question.

>     2. If Github becomes the only method of logging in then running it locally will be a pain with having someone need to register the app with github to setup the API keys etc. This isn't a problem for the Azure instance as it'll be setup once and done.

Could this be resolved by just having clearer documentation? Happy to discuss this next week in our meeting.

>     3. We still have the issue of data storage, as established in our slack comms, we will still need to store things in our DBs.

Yeah, that's fine. I think we just need to show that we're adhering to best practices/principles of data minimisation, and I can then go to IT/Legal with a stronger case.

**Comment by AoifeHughes** [comment]
Yes to discussing more next week. 

Can add documentation for this no problem, but it still creates quite a barrier of entry IMO and would require more steps and setup.

**Comment by AoifeHughes** [comment]
https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app so for each person who would rant to run this locally they'd need to follow these setup instructions to get the full functionality of this once it's implemented. I'm testing this out and experimenting with this morning

**Comment by AoifeHughes** [comment]
TODO (for me): 

- [ ] add an untracked file for `.env` to store the keys required 
- [ ] change `Login.js` to detect if the `.env` file has been set, remove local login if so, else show `Login with GitHub`
- [ ] ensure `localStorage` variables are set correctly and backend-frontend are able to communicate
- [ ] test existing functionality still works
- [ ] decide on best ways to utilise extra functionality given by GitHub access.

**Comment by chrisdburr** [comment]
> https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app so for each person who would rant to run this locally they'd need to follow these setup instructions to get the full functionality of this once it's implemented. I'm testing this out and experimenting with this morning

I think this would be fine. If someone is wanting to deploy this locally, then we can probably assume sufficient understanding to follow these instructions. And, we can support stuff like this through video demos if necessary.

**Comment by AoifeHughes** [comment]
https://github.com/alan-turing-institute/AssurancePlatform/pull/240 implements this

**Comment by kallewesterling** [comment]
👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

**Comment by kallewesterling** [comment]
Can't wait to see this in action @AoifeHughes !! <3
