### ISSUE TITLE
Allow admin(s?) to clear the database

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#181]

**Comment by AoifeHughes** [comment]
Two separate issues here, one for clearing the DB and one for allowing a user to delete their cases

**Comment by chrisdburr** [comment]
> Two separate issues here, one for clearing the DB and one for allowing a user to delete their cases

Yep, it would be really helpful to have a way for the team to know how to wipe the database, even if it's just documentation for doing this on Azure.

But, may also be helpful to have a more intuitive interface for interacting with the DB—my knowledge of SQL is patchy.

**Comment by kallewesterling** [comment]
> Two separate issues here, one for clearing the DB and one for allowing a user to delete their cases

I suggest that we split this issue up into two more manageable issues.

**Comment by kallewesterling** [comment]
- [ ] Page with select and delete cases -- with a big warning on it

Basic user can delete their own cases. If a user is marked as an admin, they can delete all cases. Group owners can delete cases in their group.

How do we mark users admins?
