### ISSUE TITLE
Develop explainer videos to help people use the methodology and platform

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#182]

**Comment by chrisdburr** [comment]
Bringing @cassgvp, @kallewesterling, and @s-laher into this issue specifically, but noting that these videos should also be designed alongside the more general skills and training documentation (see #190).

**Comment by kallewesterling** [comment]
This issue looks like it is dependent on a particular release of the platform, i.e. this work can be planned before but not recorded until we have a published version, to which these videos can belong, as guidance on how to use it.

**Comment by chrisdburr** [comment]
> Added to "Needs more info" because this issue looks like it is dependent on a particular release of the platform, i.e. this work can be planned before but not recorded until we have a published version, to which these videos can belong, as guidance on how to use it.

Yes, that's right.

**Comment by chrisdburr** [comment]
Stale. Closing.
