### ISSUE TITLE
Build in constraints for assurance case elements, including limits on characters for different fields, e.g. , )

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#183]

**Comment by chrisdburr** [comment]
This needs discussion in our weekly catch-ups. @AoifeHughes and @kallewesterling would you be happy with us having a main HackMD document for keeping track of agenda items?

**Comment by AoifeHughes** [comment]
yes!

**Comment by chrisdburr** [comment]
Great, I've setup a HackMD document: https://hackmd.io/@cburr/Hy2d2bej3

It is also set up to push/pull from this file: https://github.com/alan-turing-institute/AssurancePlatform/blob/project-admin/meeting-notes/minutes-and-agendas.md

**Comment by kallewesterling** [comment]
- [ ] some testing required to see what happens with backend if pushed beyond limits (length of fields, forbidden characters, etc)

**Comment by kallewesterling** [comment]
I think this question came up in the discussion yesterday, briefly. @AoifeHughes I think you mentioned that this may already be resolved now?

**Comment by edchapman88** [comment]
Update:
- Max character length checks were already available on the `TextInput` component (used across the `ItemEditor`).
- These checks were **not** active for the fields in the `ItemEditor`.
- With d62559c1613639e75d814369f61246cebbe695f3 I have introduced max length requirements for these fields, and they reference values in the config.json file for ease of adjustment.
- In theory, other validation checks are possible by writing a custom function and passing it to the `TextInput` components.

**Comment by kallewesterling** [comment]
I think the only reason we needed to have these limits was to ensure that nothing breaks the JSON and/or the backend database somehow. Max length was a separate issue that had to do with ensuring that the text boxes in the frontend didn't have too much text in them.

I really like how you've solved it with the config json, @edchapman88! thanks for doing that!

**Comment by kallewesterling** [comment]
This is currently a non-issue. It may come back up at some point but marking it as resolved for now.
