### ISSUE TITLE
Add all-contributors

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#187]

**Comment by AoifeHughes** [comment]
@all-contributors please add @nbarlowATI  for bugs, code, doc, design, example, ideas, testing

**Comment by AoifeHughes** [comment]
@all-contributors please add @mhauru for bugs, code, doc, design, example, ideas, testing

**Comment by AoifeHughes** [comment]
@all-contributors please add @AoifeHughes  for bugs, code, ideas, testing

**Comment by AoifeHughes** [comment]
@all-contributors please add @entopia for bugs, code, doc, design, example, ideas, testing

**Comment by AoifeHughes** [comment]
@all-contributors please add @entopia for bugs, code, doc, design, example, ideas, testing

**Comment by AoifeHughes** [comment]
@all-contributors please add @chrisdburr for bugs, code, doc, design, example, ideas, talk, user testing, research, promotion, project management

**Comment by AoifeHughes** [comment]
@all-contributors please add @cassgvp for ideas, review, project management, question

**Comment by AoifeHughes** [comment]
@all-contributors please add @kallewesterling for ideas, review, project management, question, code

**Comment by AoifeHughes** [comment]
@all-contributors please add @cassgvp for ideas, review, project management, question, events, design

**Comment by AoifeHughes** [comment]
@all-contributors please add @entopia for review

**Comment by AoifeHughes** [comment]
I made a rough attempt at this, sorry for all the pings, but please feel free to use the bot to change things up and I'll resolve any PRs

**Comment by chrisdburr** [comment]
Thanks, @AoifeHughes 🙏

**Comment by kallewesterling** [comment]
Great job - thanks @AoifeHughes !

**Comment by cassgvp** [comment]
Thanks, @AoifeHughes !

**Comment by AoifeHughes** [comment]
Need to add more recent controls

**Comment by AoifeHughes** [comment]
@all-contributors please add @aranas for ideas, review, project management, question, events, design

**Comment by AoifeHughes** [comment]
@all-contributors please add @aranas for ideas, review, project management, question, events, design

**Comment by AoifeHughes** [comment]
Closing again as sorted!

**Comment by cptanalatriste** [comment]
@all-contributors please add @cptanalatriste  for bugs, code, doc, design, example, ideas, testing
