### ISSUE TITLE
Add React tests

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#20]
Working on branch `feature/react-tests`, currently have skeleton test files for all relevant components in `src/components/test/<component>.test.js`.    Need to fill these out with (at minimum) a test that the component can render, and check that an expected bit of text is on the page.
 - [x] CaseCreator 
 - [x] CaseSelector 
 - [x] CaseContainer 
 - [x] ItemCreator
 - [x] ItemViewer 
 - [x] ItemEditor 
 - [x] Mermaid

**Comment by nbarlowATI** [comment]
More components to test:
 * [ ] ParentSelector
 * [ ] CreateGroup
 * [ ] Groups
 * [ ] Login
 * [ ] Logout
 * [ ] Signup

**Comment by AoifeHughes** [comment]
Would be great to add more tests: 
- [ ] Download and re upload outputs

**Comment by kallewesterling** [comment]
Suggestion to close this issue and be more precise with creating future issues. Rather than one "Create React tests", let's create an issue like "Create React test of download and re upload outputs"
