### ISSUE TITLE
Add a password recovery method

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#203]

**Comment by AoifeHughes** [comment]
@chrisdburr is there any reason we couldn't enforce that usernames be email addresses going forward?

**Comment by chrisdburr** [comment]
Nope. That would be fine. I think this was just a last minute feature that we had to add before the end of the last phase, so likely that the implementation is imperfect.

**Comment by AoifeHughes** [comment]
I'm putting this on hold until we find a solution on the issue of where to send reset emails from. Options include, but not limited to:
- Azure
- Run a specific SMTP server
- Python wrapped sendmail?
- SSO
