### ISSUE TITLE
Update to match with new documentation

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#211]

**Comment by AoifeHughes** [comment]
https://github.com/alan-turing-institute/AssurancePlatform/pull/210 see for the updates which @chrisdburr has made to the components used in the graphs

**Comment by chrisdburr** [comment]
Here is the current draft guidance for the site: https://github.com/alan-turing-institute/AssurancePlatform/blob/documentation/site/docs/guidance/components.md

**Comment by AoifeHughes** [comment]
@chrisdburr  Just making some of these changes now, can you confirm my understanding on what needs changed in the current setup? 
- Context + System description -> Strategy 
- Evidential claims -> Context

**Comment by AoifeHughes** [comment]
TODO: 
- [ ] increase number of unit tests for the new database layouts

**Comment by AoifeHughes** [comment]
@chrisdburr can I get your input, does this look right / thoughts on colours for strategy / anything else

<img width="694" alt="Screenshot 2023-10-09 at 11 06 09" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/166378fe-4641-4f5d-9232-5666cbcffaed">

**Comment by kallewesterling** [comment]
We have decided to move ahead with this - big merge, CI, testing will break so some work ahead. Makes backend changes. Could potentially cause trouble with existing Azure db configuration. Will take 1-2 days.
