### ISSUE TITLE
[epic] Ensure platform is ready for ethical hacking/testing

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#213]
IT suggested penetration testing of platform, if we make accessible data storage through web app.

Needs to happen before end of July, but cannot happen before we have the new system up and running.

**Comment by kallewesterling** [comment]
Chris will initiate contact with AISH around best practices.

**Comment by kallewesterling** [comment]
@chrisdburr Can you clarify what/if we need to address this issue after the conversation with AISH, especially now that we have outsourced the login authentication to GitHub's OAuth?

**Comment by chrisdburr** [comment]
From IT's perspective, they would be happy with some form of penetration testing. 

I also need to setup a conversation with legal, but I'd like to finish the work with Fruto and OCC first.

**Comment by kallewesterling** [comment]
Ok, thanks! I'll leave this in "Needs more info" and will move it to "Won't have" for now.

**Comment by kallewesterling** [comment]
Changing term in issue for sensitivity + making epic

**Comment by chrisdburr** [comment]
Closing. Will reopen with clear requirements.
