### ISSUE TITLE
Reduce data from SVG json storage POSTs

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#219]
https://github.com/alan-turing-institute/AssurancePlatform/commit/acfd9100006daf37926211488fc14b330612037a there's a way to do this more server side

**Comment by kallewesterling** [comment]
@AoifeHughes FYI, renaming with an active verb.

**Comment by kallewesterling** [comment]
@AoifeHughes correct me if I'm wrong but didn't you implement the saving of the SVG and JSON data together now?

**Comment by AoifeHughes** [comment]
yes
