### ISSUE TITLE
Add value propositions on documentation front page

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#220]
Here are some draft value propositions that can be used for the documentation and guidance site (e.g. on homepage). 

## TEA Value Propositions

- TEA platform is designed to scaffold an **open and inclusive community of practice** for the trustworthy and ethical design, development, and deployment of data-driven technologies.
- Sharing and communication of assurance cases through the TEA repository helps build **shared best practices and standards** for operationalising principles, such as sustainability, accountability, fairness, explainability, and responsible data stewardship.
- Our accessible and standardised assurance methodology, supported by clear user guidance and resources, contributes to building a more **robust and sustainable assurance ecosystem**.
- The platform comprises a responsible research and innovation (RRI) tool for developing assurance cases, a methodology and user guidance to scaffold this process, and a community-driven repository for sharing best practices.
- Instructions and support for **self-hosted deployment** are available through our documentation site for those who may need to manage sensitive information in a private environment.
- Freely available **skills and training resources** help build capacity for a more inclusive and fit-for-purpose assurance ecosystem.

They can also be used in slide decks and other forms of communication.

**Comment by kallewesterling** [comment]
Great drafts, Chris. I think, for accessibility reasons, let's expand the RRI to "Responsible Research and Innovation".

**Comment by chrisdburr** [comment]
As an idea for a possible use case, see the homepage of the static-site generator we use: https://squidfunk.github.io/mkdocs-material/

The homepage has simple propositions about the theme, which could be replicated on our homepage 

<img width="1334" alt="Screenshot 2023-08-17 at 10 08 42" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/c0eab929-6845-470a-987c-a0b266123358">

**Comment by kallewesterling** [comment]
@chrisdburr I am curious what we can do with this issue. I'd consider the value propositions reviewed now, what do we do next? Do we implement these in the documentation, the way that you've suggested in your comment above?

**Comment by kallewesterling** [comment]
Adding `documentation` tag on this issue, as it's separate from what we want our UX researchers + external devs to be working on.

**Comment by chrisdburr** [comment]
It would be helpful to have these statements (or more likely a subset of them) on the homepage of the platform, but this requires a new layout for the homepage first.

**Comment by kallewesterling** [comment]
Then, it seems like we might want to open a separate issue about remaking the homepage of the platform, for which this can be a subissue or at least have the new issue as a dependency. Does that seem right @chrisdburr ?

**Comment by chrisdburr** [comment]
> Then, it seems like we might want to open a separate issue about remaking the homepage of the platform, for which this can be a subissue or at least have the new issue as a dependency. Does that seem right @chrisdburr ?

Agreed. New issue has been created (see #302)

**Comment by chrisdburr** [comment]
@RichGriff, please could you share the homepage design you had, so @kallewesterling and I can put together some copy based on your layout and identify whether new graphics will be needed?

**Comment by RichGriff** [comment]
Sure no problem, when running the application you navigate to `/landing` this will redirect you to the example page

**Comment by kallewesterling** [comment]
First sketch done. I am working on filling these with actual content, but quickly:
- I think we should keep all the elements of the page for now, except:
    - Cut the "Menu" as this landing page will be enough for now.
    - I think the Login part on the top right of the page should be a very clear and colourful Call to Action button
    - The "social button" bar on the bottom should have two links: one to the GitHub repo and the other to the Documentation site.
    - I am wondering if we want to CC license this page as well.

![image](https://github.com/alan-turing-institute/AssurancePlatform/assets/7298727/33d71463-ca3d-4ef1-87e8-674c13a49b21)

**Comment by kallewesterling** [comment]
@chrisdburr Do you think this issue is worth closing now? Have we "added value proposition on documentation front page"?

**Comment by chrisdburr** [comment]
Yep. Looks like they're all there.
