### ISSUE TITLE
Setup versioning for platform and documentation

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#221]
Material for MK Docs supports versioning:

https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/?h=versions

Adding this issue so that we can discuss and track the following:

- Agree on semantic versioning for platform
- Integrate any necessary CI/CD for Azure deployment and containers
- Ensure documentation is consistent (will require us to get documentation to a stable version 1.0.0)

**Comment by kallewesterling** [comment]
Unclear requirements - we want some more information here.

**Comment by chrisdburr** [comment]
Closing this, having created #398
