### ISSUE TITLE
Azure variables aren't able to be set and past solution is broken

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#223]
See: 
- https://github.com/alan-turing-institute/AssurancePlatform/issues/61
- https://github.com/alan-turing-institute/AssurancePlatform/issues/14
- https://github.com/alan-turing-institute/AssurancePlatform/issues/91

Azure has ENV variables which are not being respected or set. Previously an additional script was used

Also see this file which allowed this: 
- https://github.com/alan-turing-institute/AssurancePlatform/blob/a09c9827a390f54fd597696d9f364d709757f675/frontend/build_and_run.sh

Perhaps a dedicated Docker branch for this could fix / solve issues?

This is super high priority!

**Comment by AoifeHughes** [comment]
Still can't understand how the Azure works, yet local Docker doesn't work. This is the same issue as https://github.com/alan-turing-institute/AssurancePlatform/issues/172

**Comment by chrisdburr** [comment]
> @chrisdburr I'm going to be focusing on trying to get this sorted, so the Azure implementation may go offline over next day or two as I work out some solutions. If that's a problem let me know!

Should be fine. We will need it up-and-running again by the 14th for the workshop (ideally before so we can test it and make sure it's okay).

Will we also have the new assurance elements in place by this time (e.g. strategy)?

**Comment by AoifeHughes** [comment]
> Will we also have the new assurance elements in place by this time (e.g. strategy)?
As in https://github.com/alan-turing-institute/AssurancePlatform/blob/documentation/site/docs/guidance/components.md this doc? Yes, will focus on this now
