### ISSUE TITLE
Add banner notice to platform

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#229]
As we are making (potentially breaking) changes to the platform and don't have a final code of conduct or other data/security policies, I think it would be prudent to have a notice on the welcome page acknowledging the platform is in a research preview stage.

Does grommet have something like a banner component that we can use to add a notice to the welcome page?

Example of one on the Turing Commons project pages: https://alan-turing-institute.github.io/turing-commons/

**Comment by AoifeHughes** [comment]
See https://github.com/alan-turing-institute/AssurancePlatform/tree/WIP/Banner

**Comment by kallewesterling** [comment]
Looks like #230 should close this, @AoifeHughes - so I'll go ahead and close this issue. Feel free to reopen if it was wrongly closed.
