### ISSUE TITLE
[epic] Ensure the platform adheres to the FAIR principles

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#235]
Steps
- [ ] 1: Develop criteria for implementing the FAIR principles

As discussed in #180 (now closed), we need to develop criteria for assessing the TEA platform from the perspective of the FAIR principles. A first step would be to review the FAIR principles and identify questions we could ask about the TEA platform to uncover specific actions we could take. 

https://www.go-fair.org/fair-principles/

There may be additional resources we can find that helps this process. Worth speaking with others in the TTW community: https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-fair.html

**Comment by kallewesterling** [comment]
@chrisdburr This is currently sitting in our "In Progress" -- do you have any updates on this and what you'd like us to do here? If you could clarify a bit further, that would be great. Is this about assessing the finished platform? If so, a dependency would be that we had finished the work with our UI/UX folks, probably?

**Comment by chrisdburr** [comment]
No update yet. I agree that it will need to be something we revisit after the current work with Fruto. 

There is also some work happening in the Turing Commons project about developing a similar audit, which could be useful. Again, not expecting this to be ready until early 2024.

**Comment by chrisdburr** [comment]
Closing. Stale.
