### ISSUE TITLE
Refine questions for practitioners in advance of Fruto workshop

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#236]
Creating a new issue to record questions and comments about the workshop with practitioners that is being conducted by Fruto (currently planned for 8th November, 09:30–13:30).

- What role or responsibilities do you see you, your team, or those you represent, as having within a robust and effective assurance ecosystem?
- How do you currently manage these roles and responsibilities?
- Would you characterise any of these roles and responsibilities as specifically ethical in nature?
- Are there any notable gaps in how you, your team, or those you represent, would ideally exercise such ethical responsibilities (e.g. skills, capabilities, resources, organisational readiness)?
- What benefits, if any, do you see with a structured approach to developing trustworthy and ethical assurance cases?
- Do you see any barriers or challenges to the implementation and use of trustworthy and ethical assurance cases within your team or domain?

**Comment by kallewesterling** [comment]
Refined the title.

**Comment by kallewesterling** [comment]
@chrisdburr What shall we do with this issue?

**Comment by chrisdburr** [comment]
Closing issue. Information was provided to Fruto to inform workshop planning.
