### ISSUE TITLE
Add table-reader plugin to project pages site

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#237]
MKDocs has a plugin that allows users to import data for a markdown table from a `.csv` file: https://timvink.github.io/mkdocs-table-reader-plugin/

It would be good if we could have a `.csv` file that lists the status of our user guidance and documentation sections, which we can update and use as a data source to feed into the project pages (e.g. https://github.com/alan-turing-institute/AssurancePlatform/blob/documentation/site/docs/about.md).

**Comment by chrisdburr** [comment]
I've added the `.csv` file here: https://github.com/alan-turing-institute/AssurancePlatform/blob/documentation/site/docs/module_tracker.csv

However, I can't seem to get this to work. When I try to run `mkdocs serve` locally, I get the following error.

```
ERROR    -  Config value 'plugins': The "table-reader" plugin is not installed
Aborted with 1 Configuration Errors!
```

I have run `pip install mkdocs-table-reader-plugin` and updated the `mkdocs.yml` to include the plugin as below:

```
plugins:
  - search
  - table-reader
  - tags
```

Any ideas?

**Comment by kallewesterling** [comment]
Unclear, needs more information. Leaving out of scope for next sprint.
