### ISSUE TITLE
Pre-commit is causing issues for mk docs files

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#238]
I believe the pre-commit configuration is causing issues with the formatting of markdown files used by MKDocs. 

For instance, it changes this line

```
![An illustration that shows a project team designing and developing a system. They are organised such that they form an abstract assurance case.](assets/images/building-an-assurance-case.png){ align=right width="40%" }
```

into multiple lines, as below

```
![An illustration that shows a project team designing and developing a system. They are organised such that they form an abstract assurance case.](assets/images/building-an-assurance-case.png){
align=right width="40%" }
```

But, MKDocs doesn't parse this properly when it is split across multiple lines, and so the effect is that the alignment and width attributes are not applied. 

This is just one of several issues I have noticed, but I'm struggling to understand how the pre-commit linting works or how to update the configuration. Please can we just disable it for all markdown?

**Comment by AoifeHughes** [comment]
disabled in documentation branch
