### ISSUE TITLE
Should we remove ability to login on Azure hosted platform and force GitHub login?

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#246]

**Comment by kallewesterling** [comment]
Just to note that we discussed this in the sprint planning meeting, if I remember correctly, and I suggested that there is a risk of losing some use-case scenarios where users might be on networks that block GitHub access and therefore they wouldn't be able to deploy the assurance platform in their setting. However, @AoifeHughes then remarked that there could be different options in the deployment -- if I remember correctly?

**Comment by kallewesterling** [comment]
Moving this to "Won't have" for now, as we aren't planning to remove this ability for now, if I have understood things correctly, @AoifeHughes ?

**Comment by kallewesterling** [comment]
This is in discussion currently with Kit Good. We'll have to revisit this as a user story eventually.
