### ISSUE TITLE
[epic] Make the interface available as a single electron-style app

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#248]
Would we be interested in packing the platform and database into a single electron-style app?

This could mean sharing a single app for people to use locally and means it would work without any kind of additional setup or installing if people wanted to work on something in a secure i.e., non-networked space.

**Comment by kallewesterling** [comment]
I'd say this is pretty low-priority for now, but a potentially interesting use-case for future versions. Let's keep it on our radar and discuss it when @chrisdburr is back.

**Comment by chrisdburr** [comment]
> Would we be interested in packing the platform and database into a single electron-style app?

Yes. This would be a nice portability feature for teams that want more control over self-hosting and local deployment.

But, as @kallewesterling notes, low priority for the next month or so unless it's something that needs to be coordinated alongside work from OCC.

**Comment by chrisdburr** [comment]
Closing. Not clear that this is needed.
