### ISSUE TITLE
Resolve 404 error in documentation

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#254]
Currently, the [documentation pages](https://alan-turing-institute.github.io/AssurancePlatform/) generate a 404 error when the following elements are clicked:
- "Introductory Resources" in the menu bar: https://alan-turing-institute.github.io/AssurancePlatform/introductory-resources/index.md
- "User Guidance" in the menu bar: https://alan-turing-institute.github.io/AssurancePlatform/guidance/index.md
- Logo icon (top left corner) clicked: https://alan-turing-institute.github.io (should redirect back to https://alan-turing-institute.github.io/AssurancePlatform)

Other links look like they work currently.

**Comment by kallewesterling** [comment]
Due to Chris's updates being pulled in from documentation branch prematurely (mkdocs.yml edited with links to docs that are yet to be published).

**Comment by chrisdburr** [comment]
Fixed! --> https://github.com/alan-turing-institute/AssurancePlatform/pull/282

I have added some notices to a few blank pages while the content is being drafted.

**Comment by kallewesterling** [comment]
Not fully related, but reporting it here anyway: On [this page](https://alan-turing-institute.github.io/AssurancePlatform/), there's a strange mkdocs code for formatting under the image:

<img width="626" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/7298727/0a8b262d-819d-48ee-81a8-11a3b734a46f">
