### ISSUE TITLE
Setting correct colours for components

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#256]

**Comment by kallewesterling** [comment]
- [ ] Are there colour standards associated with GSN?
- [ ] If not, we should go with a colourblindness accessible palette

**Comment by kallewesterling** [comment]
Colours are adjusted in [config.json](https://github.com/alan-turing-institute/AssurancePlatform/blob/main/frontend/src/config.json)

**Comment by kallewesterling** [comment]
FYI @AoifeHughes found #168 which I think doubles this issue.

**Comment by kallewesterling** [comment]
Response from Ibrahim:

> I am neutral on colours! As far as GSN is concerned, colours have no formal meaning in the standard notation.

**Comment by kallewesterling** [comment]
**Decision:** Let's go with a colour blindness-friendly palette.

Suggestion:

#2e2585
#337538
5da899
94cbec

**Comment by kallewesterling** [comment]
From what I can see, we need to fill out this JSON object from `config.json`:

```json
  "mermaid_item_styleclasses": {
    "classTopLevelNormativeGoal": "fill:#ff424e,color:#FFF",
    "classContext": "fill:#D17E5A,color:#FFF",
    "classSystemClaim": "fill:#3ea572,color:#FFF",
    "classProjectClaim": "fill:#9db4e6,color:#FFF",
    "classEvidentialClaim": "fill:#57847f,color:#FFF",
    "classEvidence": "fill:#155b53,color:#FFF",
    "classProjectClaimLevel1": "fill:#5986d7,color:#FFF",
    "classProjectClaimLevel2": "fill:#7a9ddd,color:#FFF",
    "classProjectClaimLevel3": "fill:#9db4e6,color:#FFF",
    "classSystemClaimLevel1": "fill:#009249,color:#FFF",
    "classSystemClaimLevel2": "fill:#24995e,color:#FFF",
    "classSystemClaimLevel3": "fill:#3ea572,color:#FFF",
    "classHighlighted": "stroke:#FF0,stroke-width:4,fill:#7700bb,color:#FF0"
  },
```

Currently, it looks like the following classes are assigned the same colours:
- `classSystemClaim` and `classSystemClaimLevel3` (#3ea572)
- `classProjectClaim` and `classProjectClaimLevel3` (#9db4e6)

...all the other colours are unique for each class, which means that we need 12-13 colours. The palette suggested only leaves us with 9.

@AoifeHughes can you remind me whether we're actually using all the classes listed above in the frontend interface right now?

**Comment by AoifeHughes** [comment]
We don't really distinguish between those two claim types, and also evidential claim was removed

**Comment by kallewesterling** [comment]
> We don't really distinguish between those two claim types

To be clear, which two claim types are you referring to?

**Comment by AoifeHughes** [comment]
whoops, sorry I mean property claim doesn't distinguish between system claim and project claim!

**Comment by AoifeHughes** [comment]
I'm updating this now - will link PR in a minute

**Comment by AoifeHughes** [comment]
![Screenshot 2023-10-24 at 09 33 35](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/83000674-84bc-423d-a10c-c900946b1048)

**Comment by AoifeHughes** [comment]
![Screenshot 2023-10-24 at 11 11 56](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/21cb8743-b75d-4d71-8cb9-6b7ae6183b2b)

Added a drop down to allow for multiple themes to be picked 

![Screenshot 2023-10-24 at 11 11 49](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/e8a61a15-d0f8-4c41-9d3f-74c61c7a29bc)

for example here is changing to white 

![Screenshot 2023-10-24 at 11 11 43](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/4e824c2b-6c04-4b7c-b971-a51a45aa8b8b)

**Comment by AoifeHughes** [comment]
For example, more profiles could be added via 

```
  "mermaid_styles": {
    "default": {
      "classTopLevelNormativeGoal": "fill:#94cbec,color:#FFF",
      "classContext": "fill:#7e2954,color:#FFF",
      "classSystemClaim": "fill:#9f4a96,color:#FFF",
      "classProjectClaim": "fill:#2e2585,color:#FFF",
      "classEvidentialClaim": "fill:#5da899,color:#FFF",
      "classEvidence": "fill:#337538,color:#FFF",
      "classProjectClaimLevel1": "fill:#2e2585,color:#FFF",
      "classProjectClaimLevel2": "fill:#2e2585,color:#FFF",
      "classProjectClaimLevel3": "fill:#2e2585,color:#FFF",
      "classSystemClaimLevel1": "fill:#dccd7d,color:#FFF",
      "classSystemClaimLevel2": "fill:#c26a77,color:#FFF",
      "classSystemClaimLevel3": "fill:#dddddd,color:#FFF",
      "classHighlighted": "stroke:#FF0,stroke-width:4,fill:#7700bb,color:#FF0",
      "classStrategy": "fill:#5da899,color:#FFF"
    },
    "inverted": {
      "classTopLevelNormativeGoal": "fill:#6B3413,color:#94cbec",
      "classContext": "fill:#81D6AB,color:#7e2954",
      "classSystemClaim": "fill:#60B569,color:#9f4a96",
      "classProjectClaim": "fill:#D1DA7A,color:#2e2585",
      "classEvidentialClaim": "fill:#A25766,color:#5da899",
      "classEvidence": "fill:#CC8AC7,color:#337538",
      "classProjectClaimLevel1": "fill:#D1DA7A,color:#2e2585",
      "classProjectClaimLevel2": "fill:#D1DA7A,color:#2e2585",
      "classProjectClaimLevel3": "fill:#D1DA7A,color:#2e2585",
      "classSystemClaimLevel1": "fill:#232382,color:#dccd7d",
      "classSystemClaimLevel2": "fill:#3D9588,color:#c26a77",
      "classSystemClaimLevel3": "fill:#222222,color:#dddddd",
      "classHighlighted": "stroke:#FF0,stroke-width:4,fill:#88FF44,color:#7700bb",
      "classStrategy": "fill:#A25766,color:#5da899"
    },
    "white": {
      "classTopLevelNormativeGoal": "fill:#FFF,color:#000",
      "classContext": "fill:#FFF,color:#000",
      "classSystemClaim": "fill:#FFF,color:#000",
      "classProjectClaim": "fill:#FFF,color:#000",
      "classEvidentialClaim": "fill:#FFF,color:#000",
      "classEvidence": "fill:#FFF,color:#000",
      "classProjectClaimLevel1": "fill:#FFF,color:#000",
      "classProjectClaimLevel2": "fill:#FFF,color:#000",
      "classProjectClaimLevel3": "fill:#FFF,color:#000",
      "classSystemClaimLevel1": "fill:#FFF,color:#000",
      "classSystemClaimLevel2": "fill:#FFF,color:#000",
      "classSystemClaimLevel3": "fill:#FFF,color:#000",
      "classHighlighted": "stroke:#000,stroke-width:5,fill:#FFF,color:#000",
      "classStrategy": "fill:#FFF,color:#000"
    }
```
