### ISSUE TITLE
Ensure text contrast is sufficient

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#269]
Accessibility issue: Currently, some colours are not sufficiently contrasting with each other which can reduce legibility on the platform.

Solution: Ensure text contrast is sufficient.

**Comment by AoifeHughes** [comment]
As per the Web Content Accessibility Guidelines (WCAG), a contrast ratio of at least 4.5:1 has been put into the PR https://github.com/alan-turing-institute/AssurancePlatform/compare/contrasts?expand=1
