### ISSUE TITLE
Improve the speed of the platform

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#290]

**Comment by AoifeHughes** [comment]
say more? Is it slow?

**Comment by kallewesterling** [comment]
This was created from the bullet points in #159. Making sure that our backlog has everything that we need/want.

**Comment by AoifeHughes** [comment]
Sure, I went through that issue, but I wasn’t clear on what could be done for this

**Comment by kallewesterling** [comment]
Closing as duplicate of #312
