### ISSUE TITLE
Change GitHub authorisation request

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#292]
~~When you currently sign-in with GitHub for the first time and it asks you to authorise, the request comes from `Aoife Hughes`. Wondering if this is something we can change?~~

Moving to [NextAuth](https://next-auth.js.org/), implementation in new system.

**Comment by AoifeHughes** [comment]
It has to be a user, there are instructions of how to change this in the docs

**Comment by AoifeHughes** [comment]
https://github.com/alan-turing-institute/AssurancePlatform/blob/main/site/docs/platform-details/github.md

**Comment by AoifeHughes** [comment]
Actually, good point, it’s slightly outdated, it now reads things from environment variables. So they’re set via them rather than directly editing the settings.py

**Comment by AoifeHughes** [comment]
- [ ] update docs to reflect and show how to build a debugging system

**Comment by AoifeHughes** [comment]
I’ve looked into this more and think orgs can host apps, from what I’ve read, if the person setting it up as permissions. I’ve reached out to the Turing people with admin for the institute to ask if they can help set it up!

**Comment by kallewesterling** [comment]
Moving this one into "Won't have" as well, as it's not something that's feasible or prioritised currently.

**Comment by kallewesterling** [comment]
Closing as we're fixing this with NextAuth
