### ISSUE TITLE
[epic] Add scratchpad to assurance case builder

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#295]
It would be a good idea to have a scratchpad that users can add temporary thoughts or comments to prior to adding them to the assurance case.

Any thoughts on how best to implement this?

Should it be a simple plain text editor, or should there be a little more structure?

**Comment by kallewesterling** [comment]
Moving this to "Won't have" for now, as it's not a prioritised issue, nor a feasible one to complete in the next sprint. It's also in "Needs more info" as we have a lot of pending questions before work can begin on these issues.

**Comment by kallewesterling** [comment]
Closing as I believe this is implemented in the new UX overhaul. There's a "Notes" feature that can be used for this purpose.
