### ISSUE TITLE
Add element identifiers

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#296]
Each of the assurance case elements should have an unique identifier. 

Ideally this would be something like the following:

- `G1` for the top-level goal
- `P1` for the first property claim
- `P1.1` for the first child of `P1`

The user should not be able to change these identifiers. Rather, they should be added programmatically.

**Comment by chrisdburr** [comment]
See this example for reference: https://safetycaseframework.aurora.tech/gsn

**Comment by chrisdburr** [comment]
Choice has been made to add button to interface that allows user to dynamically update element identifiers when they choose, rather than when an element is added/deleted.

**Comment by kallewesterling** [comment]
@chrisdburr This is something you still want/need for the platform, right? If so, can we start here with rewriting this into a user story. Here's a sh***y first draft: "As an authorised user, I want to be able to see element identifiers for all the parts of the assurance case to quickly understand their relationships."

**Comment by chrisdburr** [comment]
Yes, it's still needed and is already a part of Rich's current plan. Will work to write it up as a user story/requirement to use for sign off.

**Comment by kallewesterling** [comment]
Rewritten into a suggested user story in #438. @chrisdburr feel free to edit that one as you see fit!
