### ISSUE TITLE
Remove unnecessary UI fields

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#298]
In the element editor, we currently have the following fields:

- Title
- Short description (also used to populate tooltip on hover of element)
- Long description
- Keywords

<img width="284" alt="Screenshot 2023-11-09 at 13 54 55" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/953c42e1-4dca-4978-9ce7-3d99ba491488">

I don't think we need all of these fields. The title can be removed if we're adding an identifier (see #296) and the long description and keywords can also be removed.  The short description can then just be renamed to `$element_name$ Statement` (e.g. Goal Statement, Strategy Statement). 

For the evidence elements, a URL/DOI should still be included. 

There is likely to be an issue with how long the statements can become due to the way they're rendered in Mermaid. This was an issue we encountered previously, which is why we added short and long descriptions. However, if there was a way to only show, say, the first 100 characters and then have a tooltip display the full statement, I think this would be okay.

**Comment by kallewesterling** [comment]
Closing - let's revisit this after we have done the overhaul of the frontend
