### ISSUE TITLE
Add undo option (or notify users prior to deleting element)

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#299]
Just found out that we need this feature the hard way 😅

It would be helpful to have an undo option in case a user accidentally deletes an element, and maybe a notification that pops up to say 'Are you sure you want to delete this element'. Perhaps with a checkbox that says 'Do not ask me again'.

**Comment by kallewesterling** [comment]
Moving this to "Won't have" for now, as it's not a prioritised issue, nor a feasible one to complete in the next sprint. It's also in "Needs more info" as there are unanswered questions regarding the implementation of this.

**Comment by kallewesterling** [comment]
@chrisdburr This also needs rewriting into a user story:

"As an authorised user, I want to be able to undo my latest edits to an assurance case, so that I can avoid any mistakes to have severe consequences and delay my work."

**Comment by kallewesterling** [comment]
Closing as rewritten into #436
