### ISSUE TITLE
Fix warnings in react code

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#30]
We currently have quite a few unused functions and variables, and possibly some redundant Components (do we need both Mermaid and MermaidChart).
Would be good to remove/refactor once we have the MVP "feature complete".

**Comment by mhauru** [comment]
Partially addressed by https://github.com/alan-turing-institute/AssurancePlatform/pull/37

**Comment by kallewesterling** [comment]
@AoifeHughes Do you know if this is still an active issue?
