### ISSUE TITLE
Add option to collapse branches in diagram

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#300]
I'd recommend this as a feature to perhaps explore with OCC.

At the moment, the diagrams get very wide very quickly. 

<img width="1267" alt="Screenshot 2023-11-10 at 09 50 11" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/e712108b-c4fc-4162-a698-1414f1263893">

It would be ideal if there was a way to collapse a branch to hide all of it's children. As an example, see the safety case provided on Aurora's website for their autonomous vehicle:

https://safetycaseframework.aurora.tech/gsn

**Comment by kallewesterling** [comment]
This is implemented
