### ISSUE TITLE
Revise homepage layout

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#302]
## Summary 

The home page of the Assurance platform needs improvement and space for extra information. 

## Steps

- [x] Agree on layout
- [x] Update page to reflect design
- [x] Add relevant information (e.g. value propositions, see #220)

**Comment by chrisdburr** [comment]
I think something like the following layout would be fine (no need for the parallax effect with the hero image) 👇

https://squidfunk.github.io/mkdocs-material/

Sections could include:

1. Navbar
2. Hero image and title (CTA buttons)
3. Value propositions and screenshots/images to help explain what the TEA platform is
4. Quotes from users
5. Further information / Get Involved
6. Footer

**Comment by kallewesterling** [comment]
@chrisdburr I'd imagine this would be a fairly easy task for OCC as well, if you'd be interested in adding this to the priorities?

**Comment by chrisdburr** [comment]
Good call. Yes, let's add it to the priorities.

**Comment by kallewesterling** [comment]
Added, thanks!

**Comment by chrisdburr** [comment]
Please use this illustration for the hero image and incorporate into the design: 

![](https://raw.githubusercontent.com/alan-turing-institute/turing-commons/main/docs/assets/images/illustrations/building-an-assurance-case.png)

**Comment by kallewesterling** [comment]
To note here is also that you mentioned the video format of the illustration @chrisdburr -- just adding a note here so William (do we have his GitHub username?) can find it.

**Comment by kallewesterling** [comment]
Perfect, @WFrankishOCC -- you found the issue I had intended to tag you in :)

**Comment by chrisdburr** [comment]
See #220 for a homepage layout that has been put together.

**Comment by chrisdburr** [comment]
@kallewesterling and @RichGriff, here is the revised copy for the home page:

- **Structured Methodology.** Our platform uses a structured methodology for assurance, supported by open and accessible user resources that have been designed to help build capabilities within the assurance ecosystem.
- **Best Practices.** By facilitating the sharing and communication of assurance cases, the TEA platform enables cross-sector and multi-disciplinary forms of knowledge sharing and best practice.
- **Responsible research and Innovation.** Going beyond traditional goals such as safety or security, the TEA platform encourages teams to critically reflect and deliberate about the societal and ethical impact of their research and innovation practices.
- **Community Building.** The TEA Platform enhances the ethical design and development of data-driven technologies by fostering an open and inclusive community, committed to advancing trustworthiness.
- **Privacy and Control.** Where necessary, we provide detailed guidance and support for self-hosting to ensure that users who handle sensitive information can manage it securely and privately within their own organisation's infrastructure.
- **Training and Capacity Building.** The platform includes freely accessible training resources for a broad range of users and stakeholders, with the goal of enriching the assurance ecosystem’s capabilities.

**Comment by kallewesterling** [comment]
@chrisdburr It looks like the above copy is now on the homepage, so I have gone ahead and created two separate issues based on your comments above. With the following two issues, I believe we can close _this issue_ and go ahead and address those specifically:
- [ ] #461
- [ ] #462

**Comment by chrisdburr** [comment]
Thanks. All good.
