### ISSUE TITLE
CaseContainer is broken on Azure when adding new elements

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#306]
Everything looks fine
![Screenshot 2023-11-23 at 08 15 36](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/0a2218fb-05c9-43eb-b745-6ce987147a67)

After adding a component 
![Screenshot 2023-11-23 at 08 15 50](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/43f299f7-b1ce-447c-88b3-a333395eb4c6)

Then reloading 
![Screenshot 2023-11-23 at 08 16 07](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/bb9447d7-2900-4020-91e3-1425c0cbcf13)

**Comment by AoifeHughes** [comment]
This only happens on Azure, not locally (for me), so it's a pain to debug

**Comment by chrisdburr** [comment]
Is anyone in REG able to support? I doubt I'm going to be able to provide any meaningful support.

**Comment by kallewesterling** [comment]
If not REG, perhaps OCC would be able to provide a look at this, as a first priority, together with you @AoifeHughes? Might be a good opportunity to understand the infrastructure in which we work as well..?

**Comment by AoifeHughes** [comment]
Fixed
