### ISSUE TITLE
Unable to create new cases

### ISSUE THREAD

**Issue by WFrankishOCC** [alan-turing-institute/AssurancePlatform#317]
As of commit 45987bfb3ff03ede00f1c2a870f2cd8daf28dbb8 you cannot create new cases. I believe this is a binding issue with the inputs for the case name and description in `CaseCreator.js`.

**Comment by kallewesterling** [comment]
Looks like #320 solved this issue, is that right @WFrankishOCC?

**Comment by WFrankishOCC** [comment]
Yep, that's right.
