### ISSUE TITLE
Ensure that backend api correctly enforces authorisation for all endpoints

### ISSUE THREAD

**Issue by WFrankishOCC** [alan-turing-institute/AssurancePlatform#328]
The backend api has an [IDOR vulnerability](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/05-Authorization_Testing/04-Testing_for_Insecure_Direct_Object_References).
While the python api does enforce authorisation on the case API (e.g. `/api/cases/{id}/`), it does not do so on the endpoints for individual case items (`/api/propertyclaims/{id}/`).

The GET endpoint allows any user, including those not logged in, to query any case item, as opposed to items of cases they have access to. I think the POST, PUT and DELETE endpoints do the same but have not throroughly checked.

Because the ids for case items increase linearly, a user can easily guess ids of case items that they should not have access to.

To replicate:
1) Open the assurance platform tool and log in
1) Navigate to a case you have permission to view
1) Open the browser's dev tools window, and switch to the network tab to start recording network traffic
1) Select a case item
1) Use the dev tools network tab to obtain the GET request url for that item
1) Copy the url to another browser where you are not logged in and view the url to get the details of that case item while unauthenticated
1) Change the id in the url to another lower value to get details of other case items while unauthorised

**Comment by kallewesterling** [comment]
Potentially depending on authorisation conversation.

**Comment by edchapman88** [comment]
### Updates in PR #367:
- If a user tries to access a case that they do not have the permissions to view, they are now directed to the "not found" page. Previously, the 403 (forbidden) response was unhandled by the frontend and the UI hung on a loading screen.
- The backend endpoints for listing, posting and replying to case comments have been protected against requests from users that do not have the permissions to view the case that they correspond to.

### Why #328 cannot be closed yet:
The following backend security considerations remain:

- [ ] As mentioned in #328, the following endpoints are publicly accessible by **any** logged in user, and any user that is **not** logged in (so entirely unprotected):
    - View, edit or delete **any** of the goals in the database. (`/api/goals/<id>`)
    - View, edit or delete **any** of the property claims in the database. (`/api/propertyclaims/<id>`)
    - View, edit or delete **any** of the strategies in the database. (`/api/strategies/<id>`)
    - View, edit or delete **any** of the contexts claims in the database. (`/api/contexts/<id>`)
    - View, edit or delete **any** of the evidence in the database. (`/api/evidence/<id>`)
    - An example of how this is achieved is included below (the request can be made from the terminal without the inclusion of an authorisation token in the header). This request edits the description for property claim box 13, which in my database happens to belong to case 7:
    ```
        curl -X PUT http://127.0.0.1:8000/api/propertyclaims/13/ -H application/json -d '{"short_description": "Im an unauthenticated user"}'
- [ ] The following endpoints are also publicaly accessible by any logged in or unauthenticated user:
    - List all system users in the database. (`/api/users`)
    - List all goals in the database. (`/api/goals/`)
    - List all property claims in the database. (`/api/propertyclaims/`)
    - List all contexts in the database. (`/api/contexts/`)
    - List all strategies in the database. (`/api/strategies/`)
    - List all evidence in the database. (`/api/evidence/`)

### Why a fix requires a non-trivial refactor:
- **Case items in the database (eg. a single propery claim or goal) are not segregated by the case that they belong too.**
   - This makes it awkward to list all of the property claims in a given case, and awkward to list only the property claims belonging to the cases that a given user has permissions to see.
- **Case items maintain no reference to the case that they belong to.**
    - So when a user requests to edit a case item, there is no efficient way to determine which case the requested item belongs to, and whether the user should have access to that case.

Workarounds for these problems are possible, but it would involve repeatedly searching through all of the items in all of the cases that a user has access to in order to determine whether a user should have access to a given case item. This is very inefficient and would be slow for a large number of complex cases.

**Comment by kallewesterling** [comment]
As we're reworking the entire backend/API soon, this issue is no longer relevant.
