### ISSUE TITLE
Remove grommet components and dependencies

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#330]
The project now uses Material UI for components, instead of Grommet. 

@WFrankishOCC has switched over most of the components, but some still rely on Grommet, such as the Data Tables for comments added to assurance cases.

Following steps need to be performed:

- [ ] Audit platform for any other Grommet components
- [ ] Switch over to a Material UI component
- [ ] Remove Grommet from code base and dependencies.

**Comment by WFrankishOCC** [comment]
I think this is now limited to three components:
* Comments
* Github
* Groups
(and also some css which will no longer be needed)

**Comment by kallewesterling** [comment]
Does this (#365) mean that we can close this issue now @edchapman88 ?

**Comment by kallewesterling** [comment]
@RichGriff Do you know if we have any more Grommet dependencies in the package? I don't believe so but if you've encountered anything during your review of the code, please let me know. (I'll go ahead and close the issue so if you _have found anything, please reopen this._)
