### ISSUE TITLE
Add case svg option to card preview on user homescreen

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#331]
The new home screen for a user's assurance cases implements a Material UI Card component. 

This inlcudes a media option that can display an image.

It would be good to have this media section show a preview of the respective assurance case, perhaps using the SVG option that has been implemented.

**Comment by edchapman88** [comment]
Two different approaches to implementing this feature were briefly discussed:
1. Maintain .svg files in the database for each case, update them when the case details change, then fetch and display them when the manage cases page is rendered.
2. Generate and render the `svg` html elements on the fly from the json description for each case. They are re-generated and re-rendered whenever the manage cases page is re-rendered.

PR #371 implements 2. and closes this issue.

After some initial testing, there does not appear to be a considerable overhead to generating the svgs on the fly. The page seems to perform well.
