### ISSUE TITLE
Split case list into Mine / Shared With Me

### ISSUE THREAD

**Issue by WFrankishOCC** [alan-turing-institute/AssurancePlatform#333]
Fruto's designs for the case list have two tabs - one for your cases and one for cases shared with you, but this is not yet implemented.

![image](https://github.com/alan-turing-institute/AssurancePlatform/assets/23480328/49be162e-82d9-4989-acd6-41569a344846)

**Comment by kallewesterling** [comment]
This has now been implemented.
