### ISSUE TITLE
Add sorting to case list page

### ISSUE THREAD

**Issue by WFrankishOCC** [alan-turing-institute/AssurancePlatform#334]
Fruto's designs have a feature that lets you sort your case list, instead of the current behaviour of always sorting by creation date descending.
	
This will need backend changes to let the front end access more sortable fields, currently there is just name and created date.

![image](https://github.com/alan-turing-institute/AssurancePlatform/assets/23480328/308bc095-ebc3-4ddd-9550-84e432dceee2)

**Comment by kallewesterling** [comment]
Closed as we now have a user story describing this behaviour, #431.
