### ISSUE TITLE
Nice overflow behaviour for multi-line fields

### ISSUE THREAD

**Issue by WFrankishOCC** [alan-turing-institute/AssurancePlatform#336]
Case cards and case item descriptions, which are user controlled fields that can be long and split over many lines, both have awkward styling where they will use elipses for horizontal text overflow but are just cropped for vertical text overflow.

Unfortunately there is no trivial css solution for this.

**Comment by kallewesterling** [comment]
This is no longer relevant with our remake of the interface using Tailwind.
