### ISSUE TITLE
Documentation for MVP

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#34]
- [x] update installation instructions on main README.md
- [x] add links to more detailed backend and API docs
- [x] update API docs
- [x] Write more details in backend docs (description of settings, how to deploy)
- [x] Write developer frontend docs (description of components)
- [ ] Add user instructions (+ screenshots?) to main README.md

**Comment by chrisdburr** [comment]
Closing this issue, as it is being picked up on #190
