### ISSUE TITLE
[epic] Develop a logo for the TEA platform

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#342]
Hopefully a fun (and creative) issue to get involved with. 

We need a logo for the TEA platform. Use cases include the login page for the webiste, branding, and maybe some stickers for the upcoming AIUK stand. 

First step is to agree on the general idea. I'd suggest starting with an assurance case and trying to find ways to incorporate trustworthy and ethical concepts into it. 

Here are some ideas and prompts, including an original illustration from Jonny (mostly to help get the creative juices flowing) and some logo ideas generated by DALL-E.

<img width="809" alt="Screenshot 2024-01-11 at 10 12 27" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/21dbe62e-d599-44a0-abfb-a5c9955e9be4">

<img width="680" alt="Screenshot 2024-01-11 at 10 12 18" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/55e9071d-2a8e-4667-ad28-e62c852fb75a">

<img width="695" alt="Screenshot 2024-01-11 at 10 12 11" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/76543648-afe7-4fe5-ba07-0f723cdcf394">

![building-an-assurance-case](https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/f3330c49-f03a-4167-9b7e-4fd5a057ff0a)

**Comment by kallewesterling** [comment]
@chrisdburr - it's crazy how much the DALL-E generated logo looks like a logo I created for [a previous project](https://github.com/DHRI-Curriculum)!!

I'm excited about this though :) I have some logo design in the past - and a lot of work in Illustrator.. so I'd definitely be interested in us working through this :)

**Comment by kallewesterling** [comment]
Quotes sent out to three potential companies.

**Comment by kallewesterling** [comment]
We have received the final logotype, and they have been uploaded to the Sharepoint, see:
- unzipped directory: https://thealanturininstitute.sharepoint.com/:f:/s/tea-dh/EgHW_5RNkXlJnNT3hTjwnFsBHQGQhCo9_7vWq5_Oh3_QrQ?e=LMGBgG
- zip file: https://thealanturininstitute.sharepoint.com/:u:/s/tea-dh/EQpdmDRoHrBHsimfksEn5MoBUSgEE2GRsdMHr6qjbusmzg?e=2CtIxT
