### ISSUE TITLE
Resolve minor overflow problem on collapse

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#348]
Minor overflow (crop) problem on the graph node collapse carrot icons in some graph states (one example state is the "minimal" case init).

**Comment by edchapman88** [comment]
closed with 1b9fbe2cc3153cbf80530d0a112b54bad66b0595

**Comment by edchapman88** [comment]
closed with 1b9fbe2cc3153cbf80530d0a112b54bad66b0595
