### ISSUE TITLE
Adjust graph zoom controls bar styling.

### ISSUE THREAD

**Issue by edchapman88** [alan-turing-institute/AssurancePlatform#353]
Currently the bar takes the full screen width and limits the graph display height, cropping the bottom of the graph unnecessarily.

**Comment by kallewesterling** [comment]
Assigned you, @edchapman88 - I assume this is something you can resolve pretty easily, by the sound of it?

**Comment by edchapman88** [comment]
closed with 3dfd9f2761703d457231f97fde635d35fc2edfa6

**Comment by edchapman88** [comment]
closed with 3dfd9f2761703d457231f97fde635d35fc2edfa6
