### ISSUE TITLE
Make editor panel scrollable

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#359]
Currently, the editor panel is not scrollable. It should be, so that when the user's window is too small, like in the following image, the user can still scroll up and down in the right-hand panel.

![image](https://github.com/alan-turing-institute/AssurancePlatform/assets/7298727/66e14143-0e95-49ac-b3fd-098b1b7c671f)

**Comment by edchapman88** [comment]
closed with b387fc94c22451ca169ecc80358f796e57efa399
