### ISSUE TITLE
"Add Goal" button could be dynamic

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#375]
"Add Goal" button could be dynamic, so if you have a Goal selected, it would give options based on the selection?

**Comment by chrisdburr** [comment]
<img width="1910" alt="Screenshot 2024-04-25 at 14 21 21" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/a7001059-cc4a-4772-a46a-f9ba07c9251d">

Closing issue, as this is no longer relevant given UI redesign.
