### ISSUE TITLE
Talk to Data Safe Haven WebApp team about potential collaboration, and building a common codebase

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#4]
Both projects starting at the same time, both are development of web apps that encapsulate some process that can be expressed as a flowchart.   Would make sense to work together.

**Comment by kallewesterling** [comment]
Suggestion to close this issue, or -- if there are important remaining action items from this, to move them into a new issue (backlinking here) with an active verb in the title of the issue.
