### ISSUE TITLE
Strategy elements are not styled correctly. Text wrapping is affected.

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#404]
The text wrapping on the strategy elements (rhomboid shape) needs fixing. 

As the attached figure shows, the text spills over the side of the shape. And, the collapse button also occludes part of the text.

<img width="589" alt="Screenshot 2024-02-20 at 08 57 36" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/6ede882b-202e-4881-b2c1-2fad58b17531">

NB: worth finding alternatives to Mermaid as a priority and then only fixing this if low effort (see #391).

**Comment by kallewesterling** [comment]
Closed as outdated with new Next.js framework + TypeScript + Tailwind.
