### ISSUE TITLE
Improve "updating" indication

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#405]
When you add text to an element (via the editor side panel), there is no save button or indication to the user that their text input is being registered. See below video and note that when pressing enter a new line is added, but when deselecting the active element or selecting a new one the text is updated.

https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/e0eafa5f-e516-47ca-bec4-a6f5769aba3a

This doesn't feel like good UI/UX. My suggestion would be to either a) have the element dynamically update as the text is being added (to show the user that their changes are being registered) or to b) have the enter key be a save function (and alt + enter be a newline).

Alternative suggestions are welcome.

**Comment by kallewesterling** [comment]
Closed as rewritten into a user story in #430.
