### ISSUE TITLE
Placeholder text should be removed automatically when user selects textbox

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#407]
The current behaviour of the text input fields is a little frustrating. Rather than automatically removing the placeholder text when a user selects the field, the user has to delete the placeholder text before adding their own. See video.

https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/04845f58-3391-4a9e-88a4-2a0352cf1d77

This should be fixed to improve UI/UX.

**Comment by kallewesterling** [comment]
Closed as #429 now contains this issue in a user story.
