### ISSUE TITLE
The layout doesn't update after collapsing/contracting child elements

### ISSUE THREAD

**Issue by cptanalatriste** [alan-turing-institute/AssurancePlatform#418]
### Summary
From @chrisdburr message on Slack:

> When elements are collapsed into their parent, the space between the parent elements is not updated. The result is that the parents end up being spread widely across the viewport.

### Steps to reproduce

Please see following video: https://alanturinginstitute.enterprise.slack.com/files/U03KXHCSEHH/F072BJ7QACQ/screen_recording_2024-05-02_at_10.44.11.mov

### What you expected to happen/ what really did happen
We wanted the diagram to adjust given that child elements where collapsed, but the parent elements stayed at the same position.

### Version/ platform
The migration to JS, tested by @chrisdburr on his local machine on May 2nd 2024.

**Comment by RichGriff** [comment]
Issue here is that the toggle button on the custom nodes does not link in with the layout configuration of the nodes when they are set. 

Fix: Update the toggle function to set layouted nodes and re-work the`layoutNodesVertically` function to account for nodes that are `visible`

**Comment by RichGriff** [comment]
Fix applied in latest commit. 

@chrisdburr / @cptanalatriste can you give this an additional test for me thanks :)

**Comment by chrisdburr** [comment]
Initial testing seems to have (partially) fixed this. However, the canvas moves around in a way that is not desirable (see screen recording). 

It would be preferred to keep the node being collapsed in the same position as when the user selected it, and to have the rest of the diagram move relative to the selected node. 

@kallewesterling, I suggest this is treated as a low priority issue for now, but could be converted into a proper user story with completion conditions.

Uploading recording.mov…

**Comment by kallewesterling** [comment]
@chrisdburr Can you check whether this bug is still an active one, with the latest updates from @RichGriff? If so, I'll make sure to add it to our conversation in the sprint planning today.

**Comment by chrisdburr** [comment]
It seems to be improved, but would be helpful to review in the sprint.

**Comment by kallewesterling** [comment]
@RichGriff If you can talk a little bit to this, it'd be great!

**Comment by chrisdburr** [comment]
Happy with the solution that was presented.
