### ISSUE TITLE
[User Story]: As a user, I want to have a user feedback option on the platform

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#424]
### Role

As a user

### Desired Feature

I want to have a user feedback option on the platform

### Benefit

So that I can easily make suggestions for improvements or report bugs

### Acceptance Criteria

GIVEN I am using the platform
WHEN I encounter an issue or have a suggestion
THEN I can easily find and use a feedback option to submit my suggestions or report issues
AND I can follow simple instructions to use GitHub if the feedback option links there

### Dependencies

- [ ] Design of the feedback form/interface
- [ ] Integration of the feedback system into the current platform architecture

### Technical Notes

- Determine if the feedback link should direct users to a simple form or directly to GitHub.
- Consideration for users unfamiliar with GitHub: Provide a tutorial or simpler interface for submitting feedback.

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by kallewesterling** [comment]
@chrisdburr Please review the page and consider closing issue

**Comment by chrisdburr** [comment]
Thanks. Happy with current implementation.
