### ISSUE TITLE
[User Story]: Enhance Visual Feedback for Text Updates in Assurance Case Editor

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#430]
### Role

As an assurance case editor

### Desired Feature

I want clear visual feedback when editing text in the editor side panel

### Benefit

So that I can be confident that my changes are being saved without needing to perform additional actions like selecting another element

### Acceptance Criteria

GIVEN I am editing text in the editor side panel,
WHEN I type or make changes to the text,
THEN there should be a dynamic update or clear indication that my changes are being registered without requiring a manual save.

GIVEN I press the Enter key after typing,
WHEN the text input field is active,
THEN the `Enter` key should function as a save command, and `Alt` + `Enter` should create a new line.

GIVEN I deselect the active text element or select another element,
WHEN there have been changes made to the text,
THEN the updates should automatically save and the user should see a confirmation that the save has occurred.

### Dependencies

- [ ] Design intuitive visual feedback mechanisms

### Technical Notes

- Consider the use of visual indicators such as a color change, a check mark, or a temporary "Saved" tooltip near the text field.
- Ensure that visual feedback mechanisms, such as color changes or tooltips, comply with WCAG accessibility standards to support users with visual impairments, including those who rely on screen readers or have color vision deficiencies.
- Ensure compatibility with multiple browsers and devices to maintain a consistent user experience.
- Test the new functionality thoroughly to prevent data loss or unexpected behaviour.

### Definition of Done

- [X] The feature fulfills all acceptance criteria.
- [X] The code is reviewed and meets team coding standards.
- [X] All unit, integration, and end-to-end tests are passed.
- [X] The feature meets accessibility standards set for the project.
- [X] The code passes the CI/CD pipeline quality controls (style and linting).
- [X] The feature is merged into the main branch.
- [X] The feature is deployed and functional in the QA environment.
- [X] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
@chrisdburr I thought this was something we agreed, that the user will need to trigger the save by selecting update? This issue seems to suggest that now we want an auto save feature. This also removes the need for the alert stuff for discard changes.

**Comment by chrisdburr** [comment]
Yes, I think we can close this as an old user story that is no longer relevant and superseded by other issues that address the alerts.
