### ISSUE TITLE
[User Story]: Implement GitHub Integration for Sharing and Collaborating on Assurance Cases

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#433]
### Role

As a user of the TEA platform

### Desired Feature

I want to connect my GitHub account to share and manage assurance cases directly through public and private repositories

### Benefit

So that I can collaborate with others in the community, contribute to public resources, and manage version control of assurance cases more effectively

### Acceptance Criteria

GIVEN I am logged into the TEA platform,
AND I have connected my GitHub account,
WHEN I choose to share an assurance case,
THEN I can select from my GitHub repositories where to store the JSON file,
AND I can select if the repository is public or private,
AND the platform displays repositories as folders in the case selector interface,
AND only valid JSON files from selected repositories are shown.

### Dependencies

- [ ] OAuth integration must be established between the TEA platform and GitHub.
- [ ] Backend support for handling GitHub API requests to fetch, push, and manage files.
- [ ] A UI update for the case selector to handle repository integration.

### Technical Notes

- Ensure secure storage and handling of GitHub access tokens.
- Implement error handling for permissions and API request failures.
- Consider using GitHub’s webhooks for real-time updates on repositories.

### Definition of Done

- [X] The feature fulfills all acceptance criteria.
- [X] The code is reviewed and meets team coding standards.
- [X] All unit, integration, and end-to-end tests are passed.
- [X] The feature meets accessibility standards set for the project.
- [X] The code passes the CI/CD pipeline quality controls (style and linting).
- [X] The feature is merged into the main branch.
- [X] The feature is deployed and functional in the QA environment.
- [X] The feature was demonstrated to the team and accepted by the product owner.

**Comment by kallewesterling** [comment]
We have talked about this feature as something that will help build a community of practice, as users can share their assurance cases with selected communities on the GitHub platform. It will also enable us to build a public resource of assurance cases as users will be able to open pull requests into a public repository where we can provide (approve, really, the assurance cases in selected PRs) as examples of best practice.

Perhaps this means (as described in this user story) that there should be another page in the frontend "case selector" where users will be able to see repositories from GitHub that they have selected as available to the platform through the oAuth connection to their GitHub account, as "folders" which selectively show the valid JSON files from that repository.

**Comment by chrisdburr** [comment]
Temporarily removing from sprint while we focus on implementing the desired behaviour through the TEA platform itself, rather than through GitHub integration. 

Will leave in the backlog though, as it may still be useful to have as a future feature.

**Comment by chrisdburr** [comment]
Stale. Closing as not clear this is needed or desired.
