### ISSUE TITLE
[User Story]: Implement Commenting Feature for Enhanced Collaboration on Assurance Case Elements

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#437]
### Role

As an assurance case editor

### Desired Feature

I want to be able to comment on individual assurance case elements

### Benefit

So that I can collaborate more effectively with team members by discussing specific aspects directly within the platform

### Acceptance Criteria

GIVEN I am viewing an assurance case,
WHEN I select an assurance case element,
THEN I should have the option to add a comment to that element.
AND comments should be visible to all users with access to the assurance case.

GIVEN comments have been added to an element,
WHEN another user views the element,
THEN they should be able to see existing comments and add their own.
AND users should have the ability to reply to comments, creating threaded discussions.

### Dependencies

- [ ] Backend support for storing and retrieving comments.
- [ ] Add to user permissions a setting that ensures users can only comment if they have view or edit access to the assurance case.

### Technical Notes

- Implement comments as a linked list attached to each assurance case element to allow for scalability and real-time updates.
- Consider using a framework or library that supports real-time collaboration features.
- Ensure that the UI for comments is intuitive and integrates seamlessly with the current design of the assurance case editor.
- Comments should be timestamped and should display the name of the commenter for clarity.
- Ensure the commenting interface is designed with accessibility in mind, using high-contrast colors, scalable fonts, and keyboard navigability to comply with WCAG 2.1 guidelines.

### Definition of Done

- [X] The feature fulfills all acceptance criteria.
- [X] The code is reviewed and meets team coding standards.
- [X] All unit, integration, and end-to-end tests are passed.
- [X] The feature meets accessibility standards set for the project.
- [X] The code passes the CI/CD pipeline quality controls (style and linting).
- [X] The feature is merged into the main branch.
- [X] The feature is deployed and functional in the QA environment.
- [X] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
@cptanalatriste @chrisdburr Is this not already completed with the `Notes` button on the Action bar?

**Comment by RichGriff** [comment]
I have created the logic for viewing/editing comments on each element.

- Add a new comment
- See all comments
- Correct permissions handled for managing comments

![Image](https://github.com/user-attachments/assets/09526a54-a6c2-4e8e-a991-183c32b53d94)

Endpoints for requesting creating and updating - @cptanalatriste these are just placeholders can update to match your logic.

`/api/${entity}/${id}/comment`

`/api/${entity}/${id}/comment/${newCommentId}`

If we can get the created/updated comment back that would be great, so i can then update the collection and the assurance case.

**Comment by cptanalatriste** [comment]
@RichGriff noted, I'll start working on those. Will update you with my progress

**Comment by RichGriff** [comment]
@cptanalatriste morning carlos thats great i can take a look. 

Just a quick question, wondering why we need to pass the `type` and `id` when this info is in the request url?

**Comment by RichGriff** [comment]
Commenting on elements is now in `staging`

@chrisdburr can you please review

**Comment by cptanalatriste** [comment]
> @cptanalatriste morning carlos thats great i can take a look.
> 
> Just a quick question, wondering why we need to pass the `type` and `id` when this info is in the request url?

@RichGriff , it was because I was reusing the feature already available for commenting on Assurance Cases, as quick way of putting something into `staging`. I can update the API and avoid there redundancy.

**Comment by RichGriff** [comment]
@chrisdburr no problem will take a look at the bug

**Comment by chrisdburr** [comment]
Tested with @RichGriff during live session. All good.
