### ISSUE TITLE
Merge the `tw-conversion` with the `develop` branch and deploy the app to Azure

### ISSUE THREAD

**Issue by cptanalatriste** [alan-turing-institute/AssurancePlatform#445]

**Comment by RichGriff** [comment]
Just a small update from me. 

I have removed the following due to them not currently being used or awaiting info:

- Settings page
- Feedback Banner

These changes have also been pushed into `develop` and are now live in the staging site https://staging-assuranceplatform.azurewebsites.net/

**Comment by kallewesterling** [comment]
I'll open one (or more) new draft issue(s) about building the logic + interface for a Settings page. Then I think we can close this one.

@RichGriff -- just to be clear, is the "Feedback Banner" now instead a button in the main editor interface?
