### ISSUE TITLE
Getting homepage content

### ISSUE THREAD

**Issue by RichGriff** [alan-turing-institute/AssurancePlatform#446]
Size: large
Priority: highest

**Comment by kallewesterling** [comment]
Content drafted in:
- [ ] https://github.com/alan-turing-institute/AssurancePlatform/issues/220#issuecomment-2118209181

**Comment by RichGriff** [comment]
@kallewesterling @chrisdburr 

I have updated the landing page with the copy you have provided. Any links will need to be identified and updated.

https://staging-assuranceplatform.azurewebsites.net/
