### ISSUE TITLE
Add a feedback button to the case editor + Provide feedback button --> GitHub documentation

### ISSUE THREAD

**Issue by RichGriff** [alan-turing-institute/AssurancePlatform#448]
Size: small
Priority: highest

**Comment by RichGriff** [comment]
New link for the feedback banner 
https://alan-turing-institute.github.io/AssurancePlatform/community/community-support/

**Comment by kallewesterling** [comment]
Looks like this is ready for move to "ready for review" column, @RichGriff ?
