### ISSUE TITLE
[Bug]: Login screen flashes for the user when accessing the platform

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#450]
Currently, the login screen flashes for a user who is not yet logged in and who access the splash page (and is redirected to the login screen). This may be resolved with #447 being resolved, but wanted to report it as a bug still.

**Comment by RichGriff** [comment]
Hey @kallewesterling is this still happening?

**Comment by kallewesterling** [comment]
Just tested, nope!
