### ISSUE TITLE
Develop logic for implementation of TourGuideJS

### ISSUE THREAD

**Issue by RichGriff** [alan-turing-institute/AssurancePlatform#451]
Size: large
Priority: low

**Comment by chrisdburr** [comment]
@RichGriff, am I right in assuming you have ruled out TourGuideJS? If so, please can we close this issue and add a new dependancy to the parent user story (see #425)

**Comment by RichGriff** [comment]
@chrisdburr rule out as far as I couldn't get to work with nextjs. 

Will close this down, but as discussed this is something that needs a lot more design and possibly a different approach.
