### ISSUE TITLE
List errors where we need feedback

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#452]
Size: medium
Priority: low

**Comment by chrisdburr** [comment]
What's this issue for @kallewesterling. Please add more information.

**Comment by kallewesterling** [comment]
This is needed for [https://github.com/alan-turing-institute/AssurancePlatform/issues/435](https://github.com/alan-turing-institute/AssurancePlatform/issues/435).

**Comment by kallewesterling** [comment]
I think it's difficult to know what errors _could occur_ not knowing the code side of the frontend very well. All operations to database should probably be wrapped in `try { ... } catch(err) { ... }` statements, where `catch(err) { ... }` should generate some kind of output to the user in the front-end. CUrrently, the only error output can be observed in the browser Developer Tools.

**Comment by chrisdburr** [comment]
Stale. Closing.
