### ISSUE TITLE
Integrating logic + UI component for ability to add a URL to an Evidence element

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#453]
## Role
As an assurance case editor,

## Desired Feature
I want to add one or more URLs to each evidence element, [see #427 -- one URL is also fine!]

## Benefit
So that I can link directly to relevant resources, supporting documents, or references, thereby enhancing the credibility and traceability of the evidence.

## Acceptance Criteria

GIVEN I am logged into the TEA platform as an assurance case editor,
AND I am viewing an assurance case,
WHEN I select an evidence element within the case,
THEN I should see an option to add a URL to this element.

GIVEN I have added a URL to an evidence element,
WHEN I input a valid URL and save the changes,
THEN the URL should be visibly associated with the evidence element and clickable.

[this is lifted in from #427 -- feel free to ignore this acceptance criteria]
GIVEN I have added multiple URLs to an evidence element,
WHEN I view the evidence element,
THEN all added URLs should be listed, each being independently clickable.

GIVEN a URL has been added to an evidence element,
WHEN I choose to edit the URLs,
THEN I should have the option to remove or modify the [or each] URL.

GIVEN I attempt to add an invalid URL format,
WHEN I try to save this URL,
THEN I should receive an error message indicating the URL is not valid and the URL should not be saved.

## Dependencies

- [X] Backend API to handle URL storage and retrieval for evidence elements.
- [x] Frontend UI design must be updated to include URL addition inputs in the evidence element editor.

## Technical Notes

- [ ] Ensure URL validation logic is robust to accept only valid URLs.
- [ ] Consider the UI/UX design to accommodate multiple URLs without cluttering the interface.
- [ ] Ensure that the interface supports accessibility standards, such as keyboard navigability and screen reader compatibility.
- [ ] Implementation should be compatible with existing database schema and should consider security implications of storing and displaying external URLs.

## Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
The user now has the ability to add a single URL for the Evidence node.

Please note: I have followed the original definition for this, meaning that the user can only upload a single URL in the field for the evidence node. This assumes that the API can only handle this as a single string value and not an array (for multiple urls).



![Image](https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/5c310bc7-e610-42d8-8883-be37ab0a3b80)

**Comment by kallewesterling** [comment]
@cptanalatriste Does this follow the schema that you have set up, i.e. to be clear: **Does each Evidence element have one and only one URL associated with it?** If that's the case, I'm happy to consider DoD criteria here. If the schema has multiple URLs, we'll need to revise this story.

**Comment by kallewesterling** [comment]
_From demo just now: it looks like there's only one URL associated with each `Evidence`._
