### ISSUE TITLE
Revise FAQ on homepage

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#461]
Revise FAQ on homepage:
- [ ] Create a FAQ on our documentation site
- [ ] Removing the frequently asked questions bullet points
- [ ] Add a CTA/button that takes the user to the FAQ on the documentation site

**Comment by chrisdburr** [comment]
@RichGriff, I'd recommend we remove the FAQ from the homepage and update the previous section to include the following:

**Structured Methodology.**
Our platform uses a structured methodology for assurance, supported by open and accessible user resources designed by experts in assurance.

**Best Practices.**
Our aim is to facilitate open sharing and communication of assurance cases, to help enable cross-sector and multi-disciplinary forms of knowledge sharing and best practice.

**Responsible Research and Innovation.**
Going beyond traditional goals such as safety or security, the TEA platform encourages teams to critically reflect and deliberate about the societal and ethical impact of their research and innovation practices.

**Community Building.**
The TEA Platform aims to remove barriers to participation and contribution to assurance practices, seeking to build a diverse and inclusive community of practice.

**Privacy and Control.**
Although we promote and encourage openness and transparency, we also support self-hosting to ensure that users who handle sensitive information can manage it securely and privately within their own organisation's infrastructure.

**Training and Capacity Building.**
The platform includes freely accessible training resources for a broad range of users and stakeholders, as well as providing information about upcoming events and workshops.

**Comment by RichGriff** [comment]
Removed the FAQ section from the landing page

And updated the features with the above copy

**Comment by chrisdburr** [comment]
Thanks. PR approved (#635). Closing issue.
