### ISSUE TITLE
Revise image on homepage

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#462]
- [x] @chrisdburr will put one together for a generic AI system
- [ ] @chrisdburr pings @RichGriff when the image is ready for homepage

**Comment by chrisdburr** [comment]
Here is a generic case that can be used:

[Example Case for Homepage-2024-5-6T11-0-9.json](https://github.com/user-attachments/files/15613336/Example.Case.for.Homepage-2024-5-6T11-0-9.json)

However, I would recommend we update the homepage image using this example once the following issues have been merged

- [ ] #438 
- [ ] #470 
- [ ] #477

**Comment by chrisdburr** [comment]
Thanks. PR approved (#635). Closing issue.

**Comment by marlonscloud** [comment]
Re-opening to change title text to "AI Fairness"

**Comment by RichGriff** [comment]
All sorted and pushed into staging
