### ISSUE TITLE
[User Story]: Edit and Remove Notes in Assurance Case Editor

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#467]
### Role

As an assurance case editor

### Desired Feature

I want the ability to edit and remove notes that I have created within the "notes" functionality of the assurance case editor

### Benefit

so that I can correct errors or update the information as the case develops or my understanding changes

### Acceptance Criteria

GIVEN I have previously added a note to an assurance case,
AND I am currently viewing or editing the assurance case's notes,
WHEN I select a note that I have contributed to the conversation,
THEN I should have options to either edit or remove the note,
AND if I choose to edit, I should be able to modify the content in-place and save changes,
AND if I choose to remove, the note should be deleted immediately after confirmation.

### Technical Notes

- Implement UI components for editing and removing notes directly within the assurance case editor.
- Ensure that changes to notes are synchronised with the backend database.
- Consider implementing a confirmation dialog for removing notes to prevent accidental deletions.
- Ensure that edit and remove functionalities are accessible to all users.

### Definition of Done

- [X] The feature fulfills all acceptance criteria.
- [X] The code is reviewed and meets team coding standards.
- [X] All unit, integration, and end-to-end tests are passed.
- [X] The feature meets accessibility standards set for the project.
- [X] The code passes the CI/CD pipeline quality controls (style and linting).
- [X] The feature is merged into the main branch.
- [X] The feature is deployed and functional in the QA environment.
- [X] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
@cptanalatriste  to check `Comment` endpoint if we can `PUT` and `DELETE`

**Comment by RichGriff** [comment]
I have now implemented the following

- API now has a new endpoint for fetching a single comment as well as update and delete
- Reworked the `/comments/{assurance_case_id}/` endpoint to make this work with the above
- Ability for a user to toggle whether they would like to edit the comment or not
- Ability for a user to remove the comment

Please note: This assumes that any user with access to the case can therefore edit/delete the note. 

@cptanalatriste Can you please review the PR https://github.com/alan-turing-institute/AssurancePlatform/pull/507

**Comment by chrisdburr** [comment]
This was in `Ready` but seems like it should be `In Review`. Please can you verify @cptanalatriste?

**Comment by cptanalatriste** [comment]
Last thingI knew about this issue was a PR by @RichGriff and I requested some minor comments. However, I've seen it was already merged.

@RichGriff , shall we move this to "Review"?

**Comment by chrisdburr** [comment]
Discussed with @RichGriff. Confirmed. Closing.
