### ISSUE TITLE
[User Story]: Setup and Documentation for Azure Backend Storage

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#468]
### Role

As someone deploying the TEA platform in a local environment

### Desired Feature

I want detailed instructions on setting up Azure backend storage for storing images and screenshots

### Benefit

so that I can ensure a robust and correctly configured storage solution for my deployment of the TEA platform

### Acceptance Criteria

GIVEN I am setting up the TEA platform in a local environment,
WHEN I follow the provided documentation for setting up Azure backend storage,
THEN I should be able to configure the storage without external assistance,
AND the platform should successfully connect to and utilize Azure storage for managing images and screenshots.

### Technical Notes

- The documentation should include step-by-step setup instructions specific to Azure storage.
- Include screenshots and command-line examples where applicable.
- We need to setup proper storage accounts for staging and production.

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by kallewesterling** [comment]
While updating the Azure backend storage, @cptanalatriste + @RichGriff  -- can you make sure to document this somewhere, which would have knock-on effects for this issue!

**Comment by RichGriff** [comment]
Related to current bug https://github.com/alan-turing-institute/AssurancePlatform/issues/473

**Comment by RichGriff** [comment]
Bug fixed this was due to my account being inactive and not the code using the storage account.

**Comment by RichGriff** [comment]
@cptanalatriste you should be able to follow the below steps and to get a storage account set up:

**Create a storage account in Azure**
You should be able to create a normal storage account, nothing special here.

**Create a `container` for your new storage account**
Once you have a storage account set up you will need to have a container where all the images will be stored. 

![Image](https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/1bc64c99-6b6c-49ef-8fb2-cb066816ec0e)

**Create a SAS (Shared Access Signature) token for the account**
In order for our application to be able to connect to this storage account we need to have a token that allows us to write files to it. You should be able to search `sas` to get access from the portal its under security & networking.  Copy the below settings, however dont forget to set the correct dates.

![Image](https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/08560748-c4e2-4d60-8a0c-0f6d25b39d16)

select `Generate SAS token` and make sure you take a copy of it.

**Finally allow public access to the storage account**
This step is ensure we can access the images with a url we generate in the app to fetch the image to render. Navigate back the networking and ensure that `Enable form all networks` is checked

![Image](https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/8cc8e9a6-4fc0-4287-b0b0-152d67c4d78f)

Any issue happy to help.

**Comment by cptanalatriste** [comment]
@chrisdburr I noticed that the URLs to the case previews are not secured: If you have the link, you can access the image preview of any case ([try this](https://assuranceplatform.azurewebsites.net/_next/image?url=https%3A%2F%2Fteamedia.blob.core.windows.net%2Fsample-container%2Fchart-screenshot-case-103.png&w=1920&q=75)).

Is this acceptable? Otherwise, we might need to change the approach for storing this files.

**Comment by chrisdburr** [comment]
> Is this acceptable? Otherwise, we might need to change the approach for storing this files.

No, they should only be accessible to the case owners or others who have been granted access.

**Comment by chrisdburr** [comment]
@cptanalatriste, other than the issue with the publicly accessible images, is there anything else in this issue that remains unresolved? If not, I'm going to suggest closing this, as it seems like a low risk (i.e. accidentally discovering the public URL).

**Comment by cptanalatriste** [comment]
@chrisdburr that was the only issue. Otherwise, in both staging and production the feature is working fine, using Turing-hosted storage accounts.
