### ISSUE TITLE
[Bug]: Context displays on the wrong level

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#469]
The Context element within the TEA platform is intended to display on the same level as the Top-Level Goal to visually represent its role as an overarching condition that affects the entire assurance case. However, it currently incorrectly appears as a child element under the Top-Level Goal, which misrepresents its structural importance and can lead to confusion in understanding the case structure.

**Expected Behavior**
The Context element should appear on the same visual level as the Top-Level Goal, indicating it is not a subordinate but rather a parallel element that provides context for the entire assurance case.

**Observed Behavior**
The Context element is displayed as a child element beneath the Top-Level Goal, suggesting a hierarchical relationship that does not accurately represent its function.

![image](https://github.com/alan-turing-institute/AssurancePlatform/assets/7298727/77d46d7d-29ab-4513-ad29-b5e071dca6cd)

**Comment by chrisdburr** [comment]
Closing this, as we're going to go a different direction and place context elements within the relevant elements as attributes.
