### ISSUE TITLE
[Bug]: Squiggly lines should be straight

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#470]

**Comment by RichGriff** [comment]
@kallewesterling  So the options we have here are as follows:

Default (bezier)
<img width="1433" alt="Screenshot 2024-06-20 at 16 02 54" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/531780eb-acdd-4ba1-9009-5f40eea93da1">

Straight
<img width="1433" alt="Screenshot 2024-06-20 at 15 56 00" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/3526a1f8-67e7-441f-9e8a-14d9ab22c9d0">

Step or Smoothstep
<img width="1433" alt="Screenshot 2024-06-20 at 16 01 44" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/147b6b63-efc6-45b9-bd01-4d9cea2c0fc8">

Which would you prefer?

**Comment by chrisdburr** [comment]
Let's go for step as the default, @RichGriff, and then allow users to change this in the settings. This is planned for a later sprint (see #490).

**Comment by chrisdburr** [comment]
Closing this for now, step did not look good with multiple levels. Will give users option in future issue.
