### ISSUE TITLE
[Bug]: Revise the modal that shows when user clicks outside of edit panel

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#471]
Revise the modal that shows when user clicks outside of edit panel:
- reverse the buttons
- "Continue"  should be "Discard changes"

**Comment by RichGriff** [comment]
@kallewesterling I can easily change the text no problem. However, reversing the buttons doesnt look as good. 

Current position
<img width="633" alt="Screenshot 2024-06-20 at 15 32 05" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/b3f9b33d-b443-4e98-a5b8-40ce621f7b3b">

New position
<img width="633" alt="Screenshot 2024-06-20 at 15 33 34" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/d1ccb421-a7ff-4085-9f5c-1401692e4532">

Also the position will effect other places we use this modal - i.e when deleting a node or case

**Comment by RichGriff** [comment]
This is now in staging awaiting feedback from @kallewesterling and @chrisdburr

**Comment by chrisdburr** [comment]
Hmmm. I'm a little torn now. 

I've done a quick search on Google to see what the common design pattern is for this, and you are right @RichGriff that the current position is the default in terms of ordering and colouring.

The only other thing I've come across is to use less ambiguous language, such as with the following example:

<img width="877" alt="Screenshot 2024-06-24 at 14 52 42" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/8cfe8509-47e6-4a1a-87a3-6171b1249d86">

So, perhaps it's best to keep the original ordering, but revise the text a little to help clarify the actions.

**Comment by RichGriff** [comment]
@chrisdburr @kallewesterling so the button has changed to Discard Changes - is this ok to close or do you want to change this?

**Comment by chrisdburr** [comment]
Please update the text for this editing modal to the following:

<img width="509" alt="Screenshot 2024-06-25 at 13 40 11" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/c9945c71-2c85-4201-bfa7-444f641b2665">

**Are you sure?**
You have changes that have not been updated, would you like to discard these changes?

- Yes, discard changes!
- No, keep editing.

And, please also add a modal for when there are unsaved changes for new elements, as there is currently no pop-up (see video).

https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/9a4b8f9a-599d-4375-8a8a-a511b444c14f

And, for consistency, please update this other modal when deleting an element (and its children). There used to be a warning about deleting all elements, but it appears to have been removed:

<img width="509" alt="Screenshot 2024-06-25 at 13 40 22" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/9aa51825-e0c2-4546-befe-1d935b8f95dc">

**Are you sure?**
Deleting this element will also remove all of the connected child elements. This cannot be undone.

- Yes, delete this element!
- No, keep the element.

We will need to update the text for the latter when we have addressed issue #475.

**Comment by RichGriff** [comment]
I have updated the Alert that pops up when editing but also the one when deleting an element - as they were in the same place. @chrisdburr just need a bug/issue raised for the alert when creating an element.

**Comment by RichGriff** [comment]
PR https://github.com/alan-turing-institute/AssurancePlatform/pull/512

**Comment by RichGriff** [comment]
Now in staging to be reviewed

**Comment by chrisdburr** [comment]
Thanks, @RichGriff.

I overlooked my bad grammar in one of the modals. Sorry. Please could you update the editing warning text to the following:

> You have changes that have not been updated. Would you like to discard these changes?

**Comment by RichGriff** [comment]
In `staging` - @chrisdburr please review

**Comment by chrisdburr** [comment]
Thanks. All good.
