### ISSUE TITLE
Set up an Azure storage account for the project

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#474]
Set up an Azure storage account for the project

**Comment by chrisdburr** [comment]
@kallewesterling, what's this issue for? Please can you add further information about why this is needed.

**Comment by kallewesterling** [comment]
Currently, I believe that the "screenshots" taken by the site are saved to @RichGriff's personal Azure storage account (if I remember correctly) so we need to set up Azure storage and connect that to the frontend codebase.

**Comment by RichGriff** [comment]
This is correct. I have added some guidance to the other issue for documenting this process.

**Comment by cptanalatriste** [comment]
@chrisdburr this one has been de-prioritised many times: didn't have a chance to work on it. If you want, I can pause my work on collaboration+websockets and jump into this

**Comment by RichGriff** [comment]
@cptanalatriste it seems there is an internal server error 500 when trying to attempt to fetch a screenshot where there are multiple files.

**Comment by cptanalatriste** [comment]
@RichGriff I will take a look. Which case of giving you trouble? Or how can I reproduce the issue?

**Comment by RichGriff** [comment]
@cptanalatriste I think it was the test assurance case, and a comment on the context node. Comment id 82 I believe.

**Comment by cptanalatriste** [comment]
@RichGriff I pushed a change to `staging`, and it seems to be working. Can you have a look?

**Comment by RichGriff** [comment]
@cptanalatriste I can confirm that this is now working as expected.

**Comment by chrisdburr** [comment]
Is there anything left to test here, @cptanalatriste, or is this issue okay to close?

**Comment by cptanalatriste** [comment]
As long as @RichGriff has verified we're not using his Azure credits anymore, please go ahead and close the issue :)
