### ISSUE TITLE
[User Story]: Reattach Orphaned Assurance Case Elements

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#475]
### Role

As an assurance case editor

### Desired Feature

I want to be able to reattach orphan elements to valid parent elements

### Benefit

So that I can maintain the integrity and structure of assurance cases by ensuring all elements are properly connected and retain detached elements temporarily when their appropriate connection is uncertain

### Acceptance Criteria

GIVEN an element is currently connected to a parent,
AND the editor decides to detach this element without an immediate reconnection target,
WHEN the editor detaches the element,
THEN the system should allow the element to remain as an orphan within the project temporarily until a suitable parent is identified.

GIVEN an element has become orphaned,
AND the editor identifies a valid new parent for this orphaned element,
WHEN the editor attempts to reattach the orphaned element,
THEN the system should allow the element to be reattached to a valid new parent,
AND the updated structure should be reflected immediately in the assurance case editor.

GIVEN an orphan element exists,
WHEN the editor wishes to keep the orphan element within the case structure for future reattachment,
THEN the system should provide a temporary storage or visual/textual space where the orphan element can be accessed and managed until reattachment.

### Dependencies

-  Review and define what constitutes a "valid" parent element based on the types of assurance case elements (e.g., Property Claims can attach to Goals or Strategies, but not to Evidence). @chrisdburr / @cptanalatriste  perhaps you can help @RichGriff here?
- See also #476

### Technical Notes

- Ensure that the interface provides a clear and intuitive method for selecting and reattaching orphan elements.
- The system must validate the parent-child relationship to prevent invalid configurations.

### Definition of Done

- [x] The feature fulfills all acceptance criteria.
- [x] The code is reviewed and meets team coding standards.
- [x] All unit, integration, and end-to-end tests are passed.
- [x] The feature meets accessibility standards set for the project.
- [x] The code passes the CI/CD pipeline quality controls (style and linting).
- [x] The feature is merged into the main branch.
- [x] The feature is deployed and functional in the QA environment.
- [x] The feature was demonstrated to the team and accepted by the product owner.

**Comment by chrisdburr** [comment]
The schema that Carlos has put together should serve as our ground truth moving forward for any questions about what is considered "valid". 

@cptanalatriste, please can we get this added to the repo (maybe as a separate branch for now) so everyone has access.

**Comment by RichGriff** [comment]
<img width="524" alt="Screenshot 2024-06-20 at 16 51 47" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/2978defd-afcd-413e-a401-a19b8ea214dd">

This is a big change requires further frontend and backend development @cptanalatriste

**Comment by chrisdburr** [comment]
This is dependant on first addressing #439

**Comment by chrisdburr** [comment]
Three suggestions for current implementation:

- Change text from 'Add Existing' to 'Reattach Element(s)'
- Allow user to hide banner stating there are orphaned elements.
- Show icons of elements type, rather than specific identifier (e.g. P1) to avoid lots of the same numbers.

Still need to find out how to display existence of nested child elements when re-attaching a branch.

**Comment by RichGriff** [comment]
- ✅ Change text from 'Add Existing' to 'Reattach Element(s)'
- ✅ Allow user to hide banner stating there are orphaned elements.
- ✅ Show icons of elements type, rather than specific identifier (e.g. P1) to avoid lots of the same numbers.
- Still need to find out how to display existence of nested child elements when re-attaching a branch.

**Comment by cptanalatriste** [comment]
Closed after demo
