### ISSUE TITLE
[User Story]: Ability to reorganise Case Elements

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#476]
### Role

As an assurance case editor

### Desired Feature

I want to have the ability to move one or more elements between valid parents

### Benefit

So that I can adjust the structure of assurance cases dynamically, ensuring that each element aligns with the most appropriate parent as the case evolves

### Acceptance Criteria

GIVEN one or more elements are currently attached to a parent element,
AND another valid parent element is available for attachment,
WHEN I decide to reorganise by moving these elements to a different parent,
THEN the system should allow me to select these elements and assign them to a new valid parent.

GIVEN elements have been reassigned to a new parent,
WHEN the change is applied,
THEN the system should update the assurance case structure to reflect these new relationships,
AND ensure that all moved elements maintain their existing child elements unless explicitly removed.

GIVEN a complex assurance case with multiple nested elements,
WHEN I need to restructure significant portions of the case,
THEN the system should provide a clear and intuitive interface to select multiple elements,
AND facilitate their reassignment to new parents with minimal disruption to the overall case integrity.

### Dependencies

- The UI must be updated to accommodate the functionality for selecting multiple elements and assigning them to a new parent. @chrisdburr and @RichGriff to meet next week to discuss further

### Technical Notes

- The user interface should dynamically update to show available valid parents once an element or a group of elements is selected for reorganisation. We discussed some kind of context menu for selection in the sidebar editor.
- Implement validation logic to confirm that a new parent is appropriate for the selected elements based on the assurance case schema. (@cptanalatriste / @chrisdburr - can you help @RichGriff here if needed?)
- Ensure that when elements are moved, all associated data (such as child elements and linked evidence) is preserved and consistently reflected in the new structure.
- Ensure that the new UI components adhere to accessibility standards, allowing all users to use the features effectively.

### Definition of Done

- [x] The feature fulfills all acceptance criteria.
- [x] The code is reviewed and meets team coding standards.
- [x] All unit, integration, and end-to-end tests are passed.
- [x] The feature meets accessibility standards set for the project.
- [x] The code passes the CI/CD pipeline quality controls (style and linting).
- [x] The feature is merged into the main branch.
- [x] The feature is deployed and functional in the QA environment.
- [x] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
I have managed to get `Evidence` and `Property Claims` to move based on a item selected (a valid parent). 

@chrisdburr can a property claim be moved to another property claim?

**Comment by RichGriff** [comment]
Moving elements seems to work, however there is an issue when attempting to move say a `P1.1` or `P2.1` - I'm getting an Internal Error back from the API. I'm assuming its something to do with the identifier stuff. 

@cptanalatriste I have pushed up my latest changes to the branch, is this something you'd be able to look at?

**Comment by RichGriff** [comment]
I believe this now resolved - we can move Property Claims to other claims and strategies. As well as moving evidence to any property claim.

**Comment by chrisdburr** [comment]
Thanks, @RichGriff. 

Just flagging that we will also need to decide what happens to numbering when this occurs. Just had a user in our workshop highlight that they moved a child element (e.g. `1.2.1` of `1.2`) to a different parent (e.g. `1.4`) and the numbering didn't update. This is the expected behaviour presently, but I wonder whether we can find somewhere between triggering a whole refresh of the case, and just having specific events trigger ones. To discuss in our next sprint.

**Comment by cptanalatriste** [comment]
One bug pending, on moving an identifier updates

**Comment by cptanalatriste** [comment]
@kallewesterling @chrisdburr shall we consider this one fixed? The bug on identifier update was addressed in PR: https://github.com/alan-turing-institute/AssurancePlatform/pull/505

**Comment by chrisdburr** [comment]
Let's discuss this today, @cptanalatriste, following your ways of working discussion. I'm not sure it's fully satisfied but I'm aware other issues are open to address the more specific issues that remain.
