### ISSUE TITLE
[User Story]: Display more text in elements

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#477]
### Role

As a User

### Desired Feature

I want to be able to see more text in the elements shown in the canvas

### Benefit

So that I can more easily read and understand the argument

### Acceptance Criteria

**GIVEN** I am in the case editor screen
**AND** I have several elements added to my case
**THEN** These elements should all have the same fixed width and max height to show the same amount of text
**AND** Where the text exceeds this fixed space, then '...' should indicate that additional text is present in the element
**AND** Where the text does not fill the fixed space, then the element should have a lower height

### Technical Notes

- All elements in a row should be vertically aligned. 
- Where some elements have a larger height than others, the row can expand, but top of elements remain aligned 
- Next row should have same spacing as all other rows.

## Example

<img width="888" alt="Frame 1" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/d279dcd7-2fcf-497c-be03-cc5ea5e80e91">

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by chrisdburr** [comment]
Thanks, @RichGriff.

We've heard from users in the workshop that they would like to be able to see more text, so I suggest we also create a new issue to deal with this separately—perhaps through a tooltip that shows up on hover.

**Comment by cptanalatriste** [comment]
@kallewesterling @chrisdburr did you create the User Story? Otherwise we can keep this one to track the requested feature.

**Comment by chrisdburr** [comment]
I haven't made a user story for this yet. But I would suggest we close this one as it has, technically, been completed. I'll link back to it in the new user story.

**Comment by chrisdburr** [comment]
/
