### ISSUE TITLE
[Bug] Moving property claims does not work on certain scenarios

### ISSUE THREAD

**Issue by cptanalatriste** [alan-turing-institute/AssurancePlatform#481]
### Summary

You're not able to move Property Claims to strategies in the following scenarios:

1. Your property claim is a child of the top-level goal.
2. Your property claim is a child of another property claim.

### Steps to reproduce

In the following case:

<img width="1414" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/1616531/f78068c1-324b-4e1c-8906-c7ccc8405569">

It is not possible to move `P2` or `P1.1`

**NOTE: Moving property claims under other property claims will be addressed in other issue.**

### What you expected to happen/ what really did happen
You should be able to move `P2` or `P1.1` to either `S1` or `S2`.

### Version/ platform
Issue detected on staging, after merge https://github.com/alan-turing-institute/AssurancePlatform/commit/98d6e41d069f5d6b0fbdc3c69fc9310c06976800

**Comment by RichGriff** [comment]
I have managed to allow Property Claims to move to strategies or other claims. 
Two issues:

- Claim with 1.2 will not move to a Strategy (internal error)
- When moving a 1.2 its identifier remains the same and should update to match its parent for example 5.x

**Comment by cptanalatriste** [comment]
The following commit fixes the problem with Sub-Claims: https://github.com/alan-turing-institute/AssurancePlatform/commit/f002c727720559cec8ac02c79e7a40925a3a4c45

1. On the Front-End side, we need to clear the values of the former parent (@RichGriff , please check that the change on `NodeEdit.tsx` makes sense).
2. During the development, we found recursion errors. The issue was due to Property Claims that were parent-child of itself. I have implemented backend logic that prevents this, but it would be good to also disable this logic from the front end.
<img width="888" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/1616531/ba7ec24e-504e-4cbf-935c-f7266ceed51c">
  In the screenshot, it is possible to assign `P1.1.` to itself. @RichGriff what's the most straightforward way of dealing with this? Remove it from the combo-box? An alert message?

3. I also noticed it is not yet possible to move Property Claims to the Top-Level Goal. @chrisdburr do you need this feature? I do not think it needs much effort.

**Comment by RichGriff** [comment]
@cptanalatriste I have updated this on our bug branch https://github.com/alan-turing-institute/AssurancePlatform/commit/e3fae246e896a4d9d6c1393ab4ad4d21dc1a3caf

**Comment by RichGriff** [comment]
@cptanalatriste to look at the identifier bug below

<img width="943" alt="Screenshot 2024-06-20 at 16 47 53" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/68d86452-4f5d-46dc-928a-b9ce17b9746e">

**Comment by cptanalatriste** [comment]
@chrisdburr @kallewesterling , the fix for the bug reported by @RichGriff is already in staging. Please verify and close accordingly.

**Comment by chrisdburr** [comment]
Almost there!

However, you can't move a property claim to a goal claim. 

Please make sure that all relationships as defined in this standard are supported: https://hackmd.io/F0EeWVrxRGe8f93KGOIzjA#Relationships

**Comment by chrisdburr** [comment]
Thanks, @cptanalatriste
