### ISSUE TITLE
[User Story]: Moving Property Claims under Goals

### ISSUE THREAD

**Issue by cptanalatriste** [alan-turing-institute/AssurancePlatform#482]
### Role

As an Assurance Case Designer

### Desired Feature

I want to move Property Claims under other Property Claims

### Benefit

Reorganise the elements of my case

### Acceptance Criteria

GIVEN that I have an assurance case with Property Claims P1 and P2
WHEN I select moving `P2` under `P1`
THEN the identifier of `P2` is changed to `P1.1`
AND the renamed `P1.1` property claim is shown under  `P1` in the diagram.

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by cptanalatriste** [comment]
Implemented as part of the fix of https://github.com/alan-turing-institute/AssurancePlatform/issues/481 . Deploying to Staging pending.

**Comment by cptanalatriste** [comment]
@chrisdburr @kallewesterling , this feature is already deployed in staging. Please confirm, so we can close this issue

**Comment by chrisdburr** [comment]
@cptanalatriste: missing moving property claims under goal. 

And, please verify all other valid options are supported by referencing this standard before closing: https://hackmd.io/F0EeWVrxRGe8f93KGOIzjA

**Comment by RichGriff** [comment]
Added the ability for Property Claims to move to Goals - this was simpler than others as we only have a single goal to move to. 

This will update the goal_id property for the property claim and then re renders the chart with the new position.

This is in PR https://github.com/alan-turing-institute/AssurancePlatform/pull/511

**Comment by RichGriff** [comment]
@chrisdburr can you please review in staging

**Comment by chrisdburr** [comment]
Thanks. Confirmed.
