### ISSUE TITLE
Add the new logotype to the platform

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#486]
As we now have a new logotype for the platform, we should make sure that it's included in all places where we currently just have the name or a placeholder logotype.

The final files have been uploaded to the Sharepoint, see:

- unzipped directory: https://thealanturininstitute.sharepoint.com/:f:/s/tea-dh/EgHW_5RNkXlJnNT3hTjwnFsBHQGQhCo9_7vWq5_Oh3_QrQ?e=LMGBgG
- zip file: https://thealanturininstitute.sharepoint.com/:u:/s/tea-dh/EQpdmDRoHrBHsimfksEn5MoBUSgEE2GRsdMHr6qjbusmzg?e=2CtIxT

## Related issue:
- [X] https://github.com/alan-turing-institute/AssurancePlatform/issues/342

**Comment by chrisdburr** [comment]
This looks to have been implemented.
