### ISSUE TITLE
Reorder 'add {element}' buttons in sidebar.

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#493]
Please ensure that the sidebar buttons always follow this ordering (from top to bottom), regardless of which element is currently selected:

`Add context`
`Add strategy`
`Add property claim`
`Add evidence`

As the following screenshot shows, when adding a new element to a property claim, the first option presented is 'evidence'.

<img width="365" alt="Screenshot 2024-06-19 at 11 25 47" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/d48f1f14-65ab-447f-ab8e-d20ee05046d6">

**Comment by chrisdburr** [comment]
Please also ensure the naming convention is as follows:

- Context
- Property Claim
- Strategy
- Evidence

**Comment by RichGriff** [comment]
Fixed: Link buttons now follow the requested order.
![Uploading Screenshot 2024-06-20 at 10.11.04.png…]()

**Comment by chrisdburr** [comment]
Thanks, @RichGriff. Please can you confirm this is the case for all elements, and not just the 'Goal' element (as depicted).

**Comment by RichGriff** [comment]
@chrisdburr  yes I have added this for all elements and only showing the ones that they can link to as before

**Comment by chrisdburr** [comment]
Great. Thanks, @RichGriff.

**Comment by RichGriff** [comment]
Verified with Rich and Carlos on a development call

**Comment by cptanalatriste** [comment]
Please verify in staging

**Comment by chrisdburr** [comment]
I can confirm this is correct. Please link to relevant PR when closing issue.

**Comment by cptanalatriste** [comment]
Addressed during PR: https://github.com/alan-turing-institute/AssurancePlatform/pull/501 . Closing as agreed with @chrisdburr
