### ISSUE TITLE
[BUG] Wrong names in sidebar

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#494]
Please can we check and correct the text in the sidebar to reflect the correct names of the respective elements?

For example, the text for this `Property Claim` currently says 'goal'.

<img width="444" alt="Screenshot 2024-06-19 at 16 35 47" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/08a80ffa-ba71-4632-a3d5-63f9f1939924">

Could we also ensure the 'Update... ' button also reflects the correct text.

**Comment by cptanalatriste** [comment]
@RichGriff , I'll prepare a fix for this one

**Comment by cptanalatriste** [comment]
@chrisdburr  here are the fixed update forms. If you agree, I can merge the PR and deploy these changes to staging:

<img width="354" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/1616531/2188a1a4-a529-4f01-a5e2-7d36f06affd9">

<img width="363" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/1616531/60b0b362-5e9e-4249-aeed-120544b5484f">

<img width="359" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/1616531/ca642c48-1eb4-4e8c-a6fe-b229cf7e9a7f">

<img width="348" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/1616531/328a5f96-56fc-4e1f-9db9-396d73117726">

<img width="361" alt="image" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/1616531/dd143fe8-30db-4cf5-9198-38a0d973b382">

**Comment by chrisdburr** [comment]
Perfect! Thanks, @cptanalatriste

**Comment by cptanalatriste** [comment]
Please verify in staging

**Comment by chrisdburr** [comment]
Have verified as correct. Please link to a PR when closing.

**Comment by cptanalatriste** [comment]
Fix merged as part of PR: https://github.com/alan-turing-institute/AssurancePlatform/pull/501 

Proceeding to close the issue
