### ISSUE TITLE
[User Story]: Find elements through fuzzy search

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#499]
### Role

As a user

### Desired Feature

I want to be able to search for specific elements that I have added based on keywords

### Benefit

So that I can more easily navigate an assurance case

### Acceptance Criteria

**GIVEN** I have an assurance case with elements already added and an option to search the case
**AND** I enter a term that I believe is used in an element's description
**WHEN** I search for this term, I am presented with a list of elements that fuzzy match this search term
**AND** when I click on the relevant element, it takes me to the right place in my case

### Technical Notes

- Preference is to have a fuzzy search, rather than a strict search to make it easier for users to find terms that they are slightly unfamiliar about

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
Progress update:

- Case header now contains a search button that opens up a search dialogue
- User can scroll through the list to select node or start typing a word that is included in the description
- Once selected the dialogue will close and the user is navigated to that node in the chart

https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/1425339d-a89a-47fd-828a-209d530d891f

**Comment by RichGriff** [comment]
in`staging` - @chrisdburr can you please review, thanks.

**Comment by chrisdburr** [comment]
Nice implementation on the search functionality, @RichGriff.

Minor bug I've found in testing arises when an element that is collapsed is selected from the results (see video).

https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/b1806e2b-d476-4018-a302-8e8a5f910009

**Comment by RichGriff** [comment]
Meeting note: Fuzzy search algorithm to show elements that link to the selected element

**Comment by cptanalatriste** [comment]
@chrisdburr , there's a preliminary version of this feature on `staging`. Please take a look, and suggest changes if needed

**Comment by chrisdburr** [comment]
Let's drop back to the option of changing all elements to `visible` for now and come back to the full implementation at a later date.

**Comment by chrisdburr** [comment]
@cptanalatriste: do you recall where we got with this issue? I'm wondering if we can close it, as I've just tested it in deployment and it seems to be working.

**Comment by chrisdburr** [comment]
Stale. Closing issue.
