### ISSUE TITLE
[Bug] Nodes Edit Toggle

### ISSUE THREAD

**Issue by RichGriff** [alan-turing-institute/AssurancePlatform#509]

**Comment by RichGriff** [comment]
This is just a fix to the recent Note Edit Feature

**Comment by RichGriff** [comment]
PR https://github.com/alan-turing-institute/AssurancePlatform/pull/510

**Comment by RichGriff** [comment]
@chrisdburr can you please review in staging

**Comment by chrisdburr** [comment]
Yep. Looks to be fixed. Thanks, @RichGriff.
