### ISSUE TITLE
[BUG] Side panel does not refresh when closed.

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#514]
As the following video shows, if a user clicks on an existing element and then proceeds to add a new child element but clicks away before making any changes, the side panel remains stuck in this state. 

This causes an issue where any new element that is then selected presents this old state to the user, even if there is no child element that can be added (e.g. for evidence elements).

https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/1862ab03-3dd7-4f47-b09a-2f9b63b100dd

**Comment by RichGriff** [comment]
In `staging` - @chrisdburr please review

**Comment by chrisdburr** [comment]
Seems good from my end. Thanks.
