### ISSUE TITLE
Move staging version to main as a 'research preview'

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#531]
The current version of the TEA platform is now more stable and usable than the current version on `main`. 

I propose that we move the staging version into the main branch and make it accessible via our default URL (https://assuranceplatform.azurewebsites.net/). 

## Requirements

- [ ] Ensure a banner or some other notification is added to explain that the platform is released as a 'research preview' and not to be used for business critical use cases.

**Comment by cptanalatriste** [comment]
@chrisdburr are there any "legal" text we need to have in place? Any preference on how to show the "Research Preview" banner?

**Comment by cptanalatriste** [comment]
@RichGriff I successfully deployed the application to `production`. As agreed, I'm assigning this to you to work on the "Research Preview" banner

**Comment by RichGriff** [comment]
Banner added to Homepage

![Image](https://github.com/user-attachments/assets/ec0ded86-de5a-41dd-93f6-e39109f1d020)

@chrisdburr please confirm copy

**Comment by chrisdburr** [comment]
Great. All good.
