### ISSUE TITLE
[BUG] Unable to upload assurance case

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#535]
While looking into #462, I noticed that I was unable to upload the associated assurance case (attached here for convenience). 

@cptanalatriste was able to locate the source of the issue as some trailing commas in the json, but no error message was provided to the user. It was only discoverable through the developer console. 

May need to convert this into a user story, but logging this as a bug for now, as I'm not sure how the trailing commas got there in the first place. The original json file was exported from the TEA platform, so no trailing commas should have been added.

[Example.Case.for.Homepage-2024-5-6T11-0-9.json](https://github.com/user-attachments/files/16145956/Example.Case.for.Homepage-2024-5-6T11-0-9.json)

**Comment by cptanalatriste** [comment]
@chrisdburr , do you want to assign this bug to a sprint?

**Comment by RichGriff** [comment]
@chrisdburr @cptanalatriste Can you confirm if your still getting this error?

I just took the json file attached an it uploaded with no issue.

**Comment by cptanalatriste** [comment]
Assigning it to @chrisdburr and moving this to Ready, until confirmation the bug holds.

**Comment by chrisdburr** [comment]
Confirming I am still getting the error message with this JSON file (see video). My guess is it's just an issue with the specific JSON file, but it would be good to debug and have better error handling.

[Example.Case.for.Homepage-2024-5-6T11-0-9.json](https://github.com/user-attachments/files/16712116/Example.Case.for.Homepage-2024-5-6T11-0-9.json)


https://github.com/user-attachments/assets/221774fe-03ef-44e7-a650-b29848fde737

**Comment by chrisdburr** [comment]
Confirmed error message present when attempting upload.
