### ISSUE TITLE
Small adjustments to homepage

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#543]
@RichGriff, please could you make the following minor tweaks to the homepage, so they are reflected in the staging environment?

1. Adjust 'Now Available in Beta Release' to 'Available as a Research Preview'
2. Change the icon to the following images (white/black background may need removing).

<img width="824" alt="temp-logo" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/82b52576-851a-491d-b899-39b67040186d">

<img width="824" alt="Screenshot 2024-07-11 at 14 03 19" src="https://github.com/alan-turing-institute/AssurancePlatform/assets/63010234/c1b89b8e-ec0e-49f7-bbca-0d36bf39d487">

**Comment by RichGriff** [comment]
In `staging` - @chrisdburr please review. 

I have used the logo above for now so you have something ready for the workshop.

@cptanalatriste there is a PR for this but i cannot push to `main` as it needs to be reviewed first.

**Comment by cptanalatriste** [comment]
@RichGriff merged! This is already in Prod

**Comment by chrisdburr** [comment]
All good!
