### ISSUE TITLE
Add SVG logo to homepage and dashboard

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#555]

**Comment by chrisdburr** [comment]
@kallewesterling please can you send @RichGriff the svgs for the TEA logo?

**Comment by kallewesterling** [comment]
I'm out on holiday today but they should be on the SharePoint @chrisdburr ! I'll see if I can find a link.

**Comment by RichGriff** [comment]
@chrisdburr happy to do so once I have the correct SVG with a transparent background to go there 🙂

**Comment by chrisdburr** [comment]
Oh, sorry. I didn't realise you were still waiting on this. 

[TEA Platform Logo Design Feb 24.zip](https://github.com/user-attachments/files/16610505/TEA.Platform.Logo.Design.Feb.24.zip)

**Comment by RichGriff** [comment]
@chrisdburr how is this?

![Image](https://github.com/user-attachments/assets/a5e5f52f-ea5b-4dff-b9f3-66f149ed1815)

**Comment by chrisdburr** [comment]
Great. Thanks.
