### ISSUE TITLE
[User Story] Require email for all TEA users

### ISSUE THREAD

**Issue by cptanalatriste** [alan-turing-institute/AssurancePlatform#567]
### Role

As a TEA platform administrator

### Desired Feature

I want to be able to register the email of every TEA user.

### Benefit

So that I can uniquely identify users from multiple platforms.

### Acceptance Criteria

**GIVEN** that I'm a new user to the TEA platform
**WHEN** I'm in the sign-up form
**THEN** I'm required to provide a unique username
**AND** I am required to provide a valid email not present in the TEA database
**AND** I am required to provide a secure password
**AND** I am required to confirm the secure password provided.

**GIVEN** that I'm an existing TEA platform user
**WHEN** I'm in the "Update Profile" page
**THEN** I can provide a new unique username
**AND** I can provide a new valid email not present in the TEA database
**AND** I can provide a new secure password
**AND** I am required to confirm the new secure password provided.

**GIVEN** that I'm an existing TEA platform user, without an email
**WHEN** I interact with the TEA platform
**THEN** I'm notified I need to provide an email to continue using the TEA platform.

### Technical Notes
If we want to use email for validation or password reset, there's an [Azure service we can use](https://azure.microsoft.com/en-gb/pricing/details/communication-services/). Prices don't look bad.

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
I have added the following to help manage this story on the frontend:

- User can now login and head to `Settings` and update their `Username` and `Email Address` - email is required.
- User can also `Delete` their account from the same settings screen
- When registering a user will be asked to enter their email address

Example:
https://github.com/user-attachments/assets/7961c8b8-2a8f-4aa9-8f39-2e444fc05aed

@chrisdburr @cptanalatriste thoughts on this?

**Comment by RichGriff** [comment]
https://github.com/user-attachments/assets/ea010a74-bcd6-44d7-bbae-0e82dc55a000

**Comment by cptanalatriste** [comment]
It's looking good @RichGriff ! When working on this feature, we need to make sure is disabled for users that use GitHub for logging.

**Comment by RichGriff** [comment]
@cptanalatriste ah yes we can make it read only if they are logged in via GitHub

**Comment by cptanalatriste** [comment]
@RichGriff there's a new endpoint for changing passwords. Please check the PR https://github.com/alan-turing-institute/AssurancePlatform/pull/576 for technical details.

**Comment by RichGriff** [comment]
Change password logic added

https://github.com/user-attachments/assets/dfca7c1d-8756-4853-b875-c72dc28ae542

**Comment by RichGriff** [comment]
I'm not sure if we can really force them to enter an email address. Will need to have a think what we can do here. 

_GIVEN that I'm an existing TEA platform user, without an email
WHEN I interact with the TEA platform
THEN I'm notified I need to provide an email to continue using the TEA platform._

**Comment by cptanalatriste** [comment]
@RichGriff maybe as a first approximation, I would suggest a modal/alert box after logging, with a text going like: "To use the TEA platform collaboration features, we require your email address. Please update your profile in the Settings page", and two buttons: 1) Cancel, 2) Go to Settings.

@chrisdburr what do you think?

**Comment by chrisdburr** [comment]
Yes, this would be fine as an initial fix. Please go ahead @RichGriff

**Comment by RichGriff** [comment]
I have added this into staging. I have assumed that we always want to show this when the user navigates to the homepage and they currently dont have an email set. 

@chrisdburr please can you review, thanks.

**Comment by cptanalatriste** [comment]
@chrisdburr , I can delete your email on `staging`. What's your username?

**Comment by chrisdburr** [comment]
cburr

**Comment by chrisdburr** [comment]
Tested and working. Thanks!
