### ISSUE TITLE
[Bug] Token bug when using provider

### ISSUE THREAD

**Issue by RichGriff** [alan-turing-institute/AssurancePlatform#568]
When using the provider we cannot set the Token into local storage until we redirect the user to the dashboard. We also need to handle whether they are logging in with a session or not. 

Currently the log in works but the component on first render, has a `null` token - resulting in nothing being rendered. The user has to refresh the page to get the expected behaviour.

**Comment by RichGriff** [comment]
This needed some re-work and resulted in having to deploy multiple build to staging, due to the error only appearing in a `production` build. 

There was an issue when using the `useLoginToken` function, to read the current token in storage. Now we just check local storage directly - this has been added to the `Dashboard` and `Logout Button`

**Comment by chrisdburr** [comment]
Thanks. Closing issue.
