### ISSUE TITLE
[User Story]: Create a reviewer role and set of corresponding permissions to give select users elevated read-only access

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#569]
### Role

As an assurance case reviewer

### Desired Feature

I want to be able to have elevated read-only permissions 

### Benefit

So I can provide feedback to the primary assurance case developer

### Acceptance Criteria

**GIVEN** an assurance case has been shared with another user, who is treated as a `reviewer`
**AND** the reviewer opens the assurance case
**THEN** the reviewer can read the whole case
**AND** download the JSON
**AND** add comments to the original file

### Technical Notes

See following table of roles and permissions from #565:
 
| **Role** | **Share Assurance Case** | **Manage Assurance Case (e.g. rename/delete)** | **Edit Assurance Case (e.g. add/edit elements or branches)** | **Add Comments** | **Download** | **View Assurance Case** |
| --- | --- | --- | --- | --- | --- | --- |
| **Owner** | x | x | x | x | x | x |
| **Editor** |  |  | x | x | x | x |
| **Reviewer** |  |  |  | x | x | x |
| **Viewer** |  |  |  |  |  | x |

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by RichGriff** [comment]
@cptanalatriste I have some stuff set in staging in prep for this, just need to have an available endpoint for setting a `reviewer` and also being able to identify on the assurance case that they have reviewer permissions (as we do with edit and view)

I'm hoping to do something like this

```js
 switch (data.accessLevel) {
      case 'Read':
        newShareItem.view = true
        break;
      case 'Edit':
        newShareItem.edit = true
        break;
      case 'Reviewer':
        newShareItem.review = true
        break;
      default:
        newShareItem.view = true
        break;
    }
```

**Comment by cptanalatriste** [comment]
@RichGriff I pushed a first update to the API to `staging`. Technical details in the PR https://github.com/alan-turing-institute/AssurancePlatform/pull/588

**Comment by RichGriff** [comment]
@cptanalatriste @chrisdburr this is now in `staging`
