### ISSUE TITLE
website buttons not working

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/AssurancePlatform#571]
Currently only the "Get started" buttons of the [website](https://assuranceplatform.azurewebsites.net/) are functional.

nothing happens when clicking on:
"Documentation"
"Github"
"Learn more"
"See it in action" (view jumps to top)
"Sending us an email"(view jumps to top)
any of the socials icons in the footer (view jumps to top)

**Comment by chrisdburr** [comment]
Thanks for logging this, @aranas.

@RichGriff, please could we update these links as follows:

- Documentation: https://alan-turing-institute.github.io/AssurancePlatform/
- GitHub: https://github.com/alan-turing-institute/AssurancePlatform
- Learn More: https://alan-turing-institute.github.io/AssurancePlatform/introductory-resources/
- See it in action: https://alan-turing-institute.github.io/AssurancePlatform/guidance/case-builder/
- Sending us an email: mailto:tea@turing.ac.uk

Please remove all socials except X and GitHub.

X should go to the @turinginst page
GitHub should go to our GitHub (as above)

**Comment by RichGriff** [comment]
All links added.

@chrisdburr can you please review.

**Comment by chrisdburr** [comment]
I'm afraid I can't see any changes yet, @RichGriff. Is this meant to be live on `staging`?

**Comment by RichGriff** [comment]
@chrisdburr this is because the builds have failed will need to look into this
