### ISSUE TITLE
Useful examples/references

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#6]
Uber autonomous vehicle safety case:
[here](https://uberatgresources.com/safetycase/gsn)

Various "GSN" based tools: 
[here](https://scsc.uk/gsn?page=gsn%206tools)

**Comment by entopia** [comment]
[](https://www.codester.com/static/uploads/items/000/025/25488/preview/004.jpg)

**Comment by chrisdburr** [comment]
Closing this issue, as it is now out-of-date with current thinking and status of project.
