### ISSUE TITLE
[BUG] Sign-up is not working

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#615]
We ran an event on Thursday, where one of the CTAs was to sign-up to the TEA platform. Just checked to see if there was a reason why no one has done this and it seems the sign-up form is not working. 

You can't use GitHub, Google, or Email.

Please can we do the following:

1. Push an urgent fix for the email option. 
2. Investigate the GH authentication. I think this is already being looked at. 
3. Remove the Google option until we have this as a live option. 

Looping in @aranas for reference only.

**Comment by cptanalatriste** [comment]
@chrisdburr we're aware GitHub authentication is not working in Prod. @RichGriff is working on that.

Google Auth has been removed from the frontend already. When did you notice it?

I'll look into the registration bug. I'll be posting updates here.

**Comment by cptanalatriste** [comment]
@chrisdburr I was able to replicate the error when using spaces in the username. Without them, user creation was fine. Can you confirm this is the issue?

@RichGriff , when using spaces in the username, the server returns `BAD REQUEST` and an error message. Maybe we can show this to the user? Currently, there's no feedback that something went wrong:

![image](https://github.com/user-attachments/assets/ada0da51-599b-4c21-afe5-9e58eb30a8cf)

**Comment by chrisdburr** [comment]
Thanks @cptanalatriste. 

I can confirm the following:

- Spaces cause an issue. As you say. Possible this was my original issue.
- However, it seems like there is also some form validation not being given as feedback to the user. I tried with the following information:

```
username: fakeuser
email: fakeuser@fakemail.com
password: password123
```

This was not accepted, but no feedback was given. 

I then tried the following, which worked, but note that it is showing that I signed up with GH, which is not accurate. 

<img width="1087" alt="Screenshot 2024-09-23 at 11 18 54" src="https://github.com/user-attachments/assets/e8551978-c2c4-4aaf-b296-abbc6c49fd6e">

**Comment by RichGriff** [comment]
I will remove the google and gh options on the sign up as these should really only be on the sign in, as this process in fact 'signs them up' if they dont currently have an account.

**Comment by RichGriff** [comment]
Github authentication works in staging, so im assuming this will be resolved when pushed into prod

**Comment by RichGriff** [comment]
I have added form validation for the username field 
<img width="540" alt="Screenshot 2024-09-23 at 13 08 58" src="https://github.com/user-attachments/assets/bbde9e4a-d625-4bb9-8c48-6a5484829ebb">

**Comment by RichGriff** [comment]
@chrisdburr @cptanalatriste I cant seem to replicate the other issue, where it picked up chris's email as a GH account. I just registered with a new username and random email and the settings so me as a non GH account

<img width="875" alt="Screenshot 2024-09-23 at 13 30 39" src="https://github.com/user-attachments/assets/8484c4c2-9a10-4f97-93da-39a9d39da3c5">

**Comment by chrisdburr** [comment]
> @chrisdburr @cptanalatriste I cant seem to replicate the other issue, where it picked up chris's email as a GH account.

Hmmm. Odd. I'll do some further testing to see if I can uncover what was going on here. 

As for the frontend changes, this is great and should catch most of the issues. Thanks, @RichGriff.

@cptanalatriste, could we look to bring these changes from staging into prod as a priority?

**Comment by cptanalatriste** [comment]
@chrisdburr , I did the deployment to prod, and it seems to be working now (user validation and GitHub login). Thanks @RichGriff for the fix!

Can you give it a try @chrisdburr ? And if it's working, feel free to close the issue
