### ISSUE TITLE
version control for database

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#62]
Can we store all revisions of DB objects, allowing rollback etc.

Built-in postgres tool?   Liquibase?
Or dramatic changes to our schema?

**Comment by chrisdburr** [comment]
Would storage of all DB objects in effect modularise the assurance case, such that reverting to, say, version 11 of a system property claim from version 15, lead to broken links with the nodes children (e.g. evidence that was only added post version 13)?
