### ISSUE TITLE
[BUG] Reviewer role cannot add comments to an assurance case

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#627]
Just tested the new comments feature for individual elements, which is part of #437.

All good in terms of the UI, but the 'Reviewer' role is not able to add comments to an assurance case that has been shared with them. They can view them, but not add their own.

A reviewer should be able to add global and local (i.e. per element) comments.

'Editor' role can read and add ✅
'Viewer' role can only read ✅

**Comment by RichGriff** [comment]
@chrisdburr the editor can make changes as I tested this, however i forgot about the reviewer role. So will put in the check for this role as well as edit.

**Comment by cptanalatriste** [comment]
Hi @RichGriff , I did add the logic that only the author of the comment can modify it or delete. @chrisdburr , is this the intended behaviour?

Also, when retrieving comments from the API each comment includes its author, so I imagine is possible to compare if it matches the user currently logged. Do you need anything else to implement the feature?

<img width="445" alt="image" src="https://github.com/user-attachments/assets/ff5ac279-5196-4183-8907-8cf0e96fabf5">

**Comment by RichGriff** [comment]
We do get the logged in user but this is for other purposes and we don't store the user. 

I'll take a look at storing this user in the state instead and then hopefully can check that when rendering comments.

Will check if username and author are equal.

**Comment by RichGriff** [comment]
For some reason I couldnt get the user stored in the state, however I have managed to fetch the current user and do a check to see if they can edit the comment.

This fix is now in `develop` and should be available in `staging` shortly.

@chrisdburr ready for you to review.

**Comment by chrisdburr** [comment]
> Hi @RichGriff , I did add the logic that only the author of the comment can modify it or delete. @chrisdburr , is this the intended behaviour?

Yes, @cptanalatriste , that's the intended behaviour. 

Tested on my end and looks good to me. Thanks @RichGriff.
