### ISSUE TITLE
Image placeholder

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#644]
### User Role

Developer

### Goal / Desire

As a developer, I want to add a loading animation to images that are loading

### Benefit / Reason

so that the UI loads in a more asthetic fashion

### Acceptance Criteria

- [ ] When images are loading, an animation / spinner shows for each one until loaded

**Comment by RichGriff** [comment]
@chrisdburr this is now in staging

**Comment by chrisdburr** [comment]
All working. Thanks.
