### ISSUE TITLE
Reload CaseSelector on case add/delete

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/AssurancePlatform#66]
Currently when one creates or deletes a case, the CaseSelector drop down at the top is not reloaded, and hence doesn't show the changes.

**Comment by mhauru** [comment]
I've been thinking about this one, and it's actually quite tricky. CaseSelector gets the cases it should list from the backend. A priori, it has no way of knowing that there's now a new case in the database, or that a case has been removed.

The conceptually right thing would be for the backend to do some sort of push to let CaseSelector know that the available cases have changed, but that's a whole different type of communication system between the front and the backend, which seems like overkill for solving such a small problem.

The less elegant solution would be that CaseCreator and the function that deletes cases inform CaseSelector that the case set has changed, "hey you should reload from the backend". But these elements are distant cousins in the React component tree, so how do you make one pass information to the other?

I think there might be some solution where somewhere at the root of the tree we create either a React `ref` or some dummy state the only purpose of which is to trigger rerenders (this may be relevant: https://reactjs.org/docs/forwarding-refs.html). And then we pass that state or ref down the React component tree to both the CaseSelector in the nav bar and the elements that create/destroy cases, and then one can change the state or call `forceUpdate` using the ref to force rerender of the other. But this sounds pretty complicated for such a simple problem, too.

There could also be some _really_ inelegant solution of bypassing the whole React tree and using something like `document.getElementById` to get a reference to the navbar CaseSelector in the case creator/deletor objects, and then use that somehow to trigger the rerender. This would be conceptually really ugly, but short in code. I'm also not sure if this is actually possible in React.

I guess we could also trigger some sort of global rerender when a case is created/deleted, so that the whole page, including the navbar, gets rerendered. Not sure if I find this to be the ugliest or the most beautiful solution. It's kinda brutal, but very simple.

@nbarlowATI, any ideas?

**Comment by nbarlowATI** [comment]
Hmm....  yes, I think your last idea, to refresh the list every time the CaseSelector component gains focus, might be the best solution...
Otherwise, I think it would be possible to have another component such as CaseCreator pass messages upstream via props to a common ancestor of CaseCreator and CaseSelector (which we would have to invent), and from that common ancestor, pass the message downstream to CaseSelector, again via props...  But I agree that this sounds messy!
