### ISSUE TITLE
Mermaid syntax error

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/AssurancePlatform#74]
Managed to generate this
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/5229876/160597350-443fd592-47c5-435a-b1c5-137359df46b5.png">
Not sure what I did, but I still have the case that causes this, so will investigate.

**Comment by mhauru** [comment]
This is caused by special characters in item names. In this case I had a semicolon (;) in there, and it messed up the Markdown. We need to sanitise names, but that's going to require some thought because the we have to adapt the sanitation to Mermaid's specific needs.

**Comment by nbarlowATI** [comment]
I think it would already be useful to just strip out semicolons and parenthesis.   We might want to do something more comprehensive / cleverer later on, but it would anyway be good to have a skeleton text-sanitizing function...  I'll have a go at starting on this.

**Comment by mhauru** [comment]
Closed by https://github.com/alan-turing-institute/AssurancePlatform/pull/93
