### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#8]
# Information about assurance case elements

These are the basic elements of an assurance case (w/ relations). 
The number for each element corresponds to its order in the argument (i.e., 1 (goal) is the top-level element). 

## Goal Elements

1. Top-Level Normative Goal (may be possible to have multiple goals in future version)
1a. System Description -> 1 (Goal)
1b. Context -> 1 (Goal)

## Claims 

2. Property Claim (Possible Types: System, Project) -> 1 (Goal) 

3. Sub-Claim (Possible Types: System, Project) -> 2 (and also be loosely grouped together)
4. Argument -> Set of/ or specific claim(s) or subclaim(s) (2 and 3)
5. Evidential Claim -> 2, 3, or 4

## Artefacts

6. Evidence -> 5 (Evidential Claim)

## Images (Examples)

<img width="868" alt="interpretability" src="https://user-images.githubusercontent.com/63010234/137942124-ae36274e-9f82-4584-a390-f385f9692f21.png">

<img width="321" alt="ethical-assurance-directed" src="https://user-images.githubusercontent.com/63010234/137942104-12f59483-c746-4d53-994b-30065a3c3aa1.png">

<img width="551" alt="goal-context" src="https://user-images.githubusercontent.com/63010234/137942184-561b078e-93d7-4763-a865-7a0a0cdc150c.png">

**Comment by mhauru** [comment]
Notes from a 2022-04-04 meeting:
* Only evidential claims and evidential artefacts can have multiple parents.
* Their parent claims can be at different levels.
* Property claims can't have multiple parents.
* Arguments can be removed as type.

**Comment by kallewesterling** [comment]
Suggestion to close this issue, or -- if there are important remaining action items from this, to move them into a new issue (backlinking here) with an active verb in the title of the issue.
