### ISSUE TITLE
Add "level" field to at least PropertyClaim/EvidentialClaim tables

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#80]
If we are to have PropertyClaims and Evidence with multiple parents, and potentially nested PropertyClaims, we do want to enforce a rule that all the parents of a PropertyClaim/Evidence are at the same "level" on the chart, i.e. the same number of steps back from the Goal.
* Should we just add this field to the tables that will directly use it (PropertyClaim/EvidentialClaim), or should we also add it to other fields in order to make it easier to propagate (easiest way for an EvidentialClaim to know what level it is, is to know what level its parent Argument was)?

**Comment by mhauru** [comment]
Started work in this at https://github.com/alan-turing-institute/AssurancePlatform/pull/86

For now I'm going with the design that all item models would have a level field. I'm hoping to automate as much as possible checking that parents are always separated by exactly one level from children, but it's work in progress, let's see if I'm overly ambitious.

**Comment by mhauru** [comment]
Closed by https://github.com/alan-turing-institute/AssurancePlatform/pull/86
