### ISSUE TITLE
Allow a PropertyClaim to be a parent/child of a PropertyClaim

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#81]
We should be able to have nested PropertyClaims.   This will require a schema change, possibly some protection against cycles, and a change to the logic of `jsonToMarkdown` in the frontend.   
* Possibly use newly introduced "level" field (see #80).

**Comment by mhauru** [comment]
Closed by https://github.com/alan-turing-institute/AssurancePlatform/pull/86
