### ISSUE TITLE
Allow PropertyClaim and EvidentialClaim to have parent/child relationship without intermediate Argument

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AssurancePlatform#82]
* Allowed children types of PropertyClaim are PropertyClaim, Argument, EvidentialClaim
* Allowed parent types of EvidentialClaim are Argument, PropertyClaim.

**Comment by mhauru** [comment]
After further discussion, we decided to just get rid of the Argument item type.

**Comment by mhauru** [comment]
Closed by https://github.com/alan-turing-institute/AssurancePlatform/pull/98
