### ISSUE TITLE
Constrain width of the evidential artefacts

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#95]
**Issue:** the width of the evidential artefact icon does not appear to have a constraint on its horizontal width, which leads to overspill (as below)

<img width="455" alt="Screenshot 2022-04-05 at 13 28 56" src="https://user-images.githubusercontent.com/63010234/161753911-3e1341b0-82e1-4603-8494-3bbbbee4c413.png">

**Suggested actions:**

- [ ] Implement a maximum horizontal and vertical width for all elements
- [ ] Implement a maximum word count for all text boxes (i.e., title, short description, long description)

**Comment by mhauru** [comment]
Maximum character counts are currently enforced at the database levelt, 200 for name, 1000 for short description, 3000 for long.

How would we like to present longish names, and how long is too long? Word wrapping would probably be the obvious first step, unless we want to restrict to really short names.

**Comment by nbarlowATI** [comment]
To implement a maximum number of characters for the text inside a box in the Mermaid chart, it is straightforward just to set some value in the `config.json` and then use this in the `makeBox` function in `utils.js`, adding an ellipsis if the text overruns this limit.  (Currently not taking account of line-breaks).
However, we would also like to make all boxes the same width, with centered text.   
There are a couple of potential approaches to this:
1) add padding spaces either side of the text, to take it up to the same number of characters as the max.
2) use <center>text here </center> html tags in the boxes.
3) use css - it is possible to define and use css classes in the markdown.

HOWEVER:
For 1), it looks like spaces are not necessarily the same width as text characters, so the boxes are not exactly the same width.
For 2), although we _can_ put html tags in the box text, the `<center></center>` ones seem to be ignored.
For 3), the only bit of CSS styling that _hasn't_ worked for me so far is `text-align:center` - if we specify e.g. `width:200px` then the text seems to be left aligned, and furthermore the boxes are slightly offset from one another horizontally.

So 1) seems to be the least-worst option for now.   Implementing this (but leaving some placeholder CSS so we are able to e.g. change box colour later on).

**Comment by mhauru** [comment]
Awwww, so close with 3... CSS strikes again.
